using System;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ValveResourceFormat.SourceGenerators;

/// <summary>
/// Generates the constructor that reads a <c>[KV3Transfer]</c> type from its KeyValues3 data.
/// </summary>
/// <remarks>
/// Every auto-property declared in the attributed declaration is read from the key named by ValveKeyValue's
/// <c>[KVProperty]</c>, or by the naming rule in <see cref="DefaultKey"/>, and <c>[KVIgnore]</c> skips one.
/// A missing key leaves the
/// property at its initializer, which is how schema defaults are expressed. The read call follows from the
/// property type. Custom loading goes in the generated <c>OnLoaded</c> partial method.
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class KV3TransferGenerator : IIncrementalGenerator
{
    private const string AttributeNamespace = "ValveResourceFormat.Serialization.KeyValues";
    private const string TransferAttributeName = AttributeNamespace + ".KV3TransferAttribute";
    private const string PropertyAttributeName = "ValveKeyValue.KVPropertyAttribute";
    private const string IgnoreAttributeName = "ValveKeyValue.KVIgnoreAttribute";
    private const string KVObjectName = "ValveKeyValue.KVObject";
    private const string KVObjectType = "global::ValveKeyValue.KVObject";

    private const string AttributesSource = $$"""
        // <auto-generated/>
        #nullable enable

        namespace {{AttributeNamespace}}
        {
            /// <summary>Generates a constructor reading the type's auto-properties from KeyValues3 data.</summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, Inherited = false)]
            internal sealed class KV3TransferAttribute : global::System.Attribute
            {
            }
        }
        """;

    private static readonly DiagnosticDescriptor UnsupportedType = new(
        "VRFKV3001",
        "Unsupported KV property type",
        "Property '{0}' has type '{1}', which KeyValues deserialization does not know how to read",
        "KV3Transfer",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor NestedType = new(
        "VRFKV3002",
        "Nested KV3 transfer type",
        "KV3 transfer type '{0}' is nested in another type, which is not supported",
        "KV3Transfer",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context => context.AddSource("KV3TransferAttributes.g.cs", SourceText.From(AttributesSource, Encoding.UTF8)));

        var types = context.SyntaxProvider.ForAttributeWithMetadataName(
            TransferAttributeName,
            static (node, _) => node is TypeDeclarationSyntax,
            static (context, cancellationToken) => Generate((TypeDeclarationSyntax)context.TargetNode, (INamedTypeSymbol)context.TargetSymbol, context.SemanticModel, cancellationToken));

        context.RegisterSourceOutput(types, static (context, result) =>
        {
            foreach (var diagnostic in result.Diagnostics)
            {
                context.ReportDiagnostic(diagnostic);
            }

            if (result.Source != null)
            {
                context.AddSource(result.HintName, SourceText.From(result.Source, Encoding.UTF8));
            }
        });
    }

    private sealed class Result(string hintName, string? source, ImmutableArray<Diagnostic> diagnostics)
    {
        public string HintName { get; } = hintName;
        public string? Source { get; } = source;
        public ImmutableArray<Diagnostic> Diagnostics { get; } = diagnostics;
    }

    private static Result Generate(TypeDeclarationSyntax declaration, INamedTypeSymbol type, SemanticModel model, System.Threading.CancellationToken cancellationToken)
    {
        var hintName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", "").Replace('<', '_').Replace('>', '_') + ".KV3Transfer.g.cs";
        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();

        if (type.ContainingType != null)
        {
            diagnostics.Add(Diagnostic.Create(NestedType, declaration.Identifier.GetLocation(), type.Name));
            return new Result(hintName, null, diagnostics.ToImmutable());
        }

        var body = new StringBuilder();

        foreach (var member in declaration.Members)
        {
            cancellationToken.ThrowIfCancellationRequested();

            if (member is not PropertyDeclarationSyntax propertySyntax || !IsAutoProperty(propertySyntax))
            {
                continue;
            }

            if (model.GetDeclaredSymbol(propertySyntax, cancellationToken) is not IPropertySymbol property || property.IsStatic || HasAttribute(property, IgnoreAttributeName))
            {
                continue;
            }

            var key = Literal(GetKey(property));
            var read = ReadExpression(property.Type);

            if (read == null)
            {
                diagnostics.Add(Diagnostic.Create(UnsupportedType, propertySyntax.Identifier.GetLocation(), property.Name, property.Type.ToDisplayString()));
                continue;
            }

            body.Append(FormattableString.Invariant($"        if (data.ContainsKey({key}))\n"));
            body.Append("        {\n");
            body.Append(FormattableString.Invariant($"            {property.Name} = {string.Format(CultureInfo.InvariantCulture, read, key)};\n"));
            body.Append("        }\n\n");
        }

        var keyword = type.TypeKind == TypeKind.Struct
            ? (type.IsReadOnly ? "readonly partial struct" : "partial struct")
            : "partial class";
        var constructorAccess = type.IsAbstract ? "protected" : "public";
        var baseCall = HasDataConstructor(type.BaseType) ? " : base(data)" : string.Empty;

        var source = new StringBuilder();
        source.Append("// <auto-generated/>\n");
        source.Append("#nullable disable\n");
        source.Append("using ValveResourceFormat.Serialization.KeyValues;\n\n");

        if (!type.ContainingNamespace.IsGlobalNamespace)
        {
            source.Append(FormattableString.Invariant($"namespace {type.ContainingNamespace.ToDisplayString()};\n\n"));
        }

        source.Append(FormattableString.Invariant($"{keyword} {type.Name}\n"));
        source.Append("{\n");
        source.Append(FormattableString.Invariant($"    /// <summary>Reads the {type.Name} from its KeyValues3 data.</summary>\n"));
        source.Append(FormattableString.Invariant($"    {constructorAccess} {type.Name}({KVObjectType} data){baseCall}\n"));
        source.Append("    {\n");
        source.Append(body);
        source.Append("        OnLoaded(data);\n");
        source.Append("    }\n\n");
        source.Append("    /// <summary>Runs after the generated properties are read.</summary>\n");
        source.Append(FormattableString.Invariant($"    partial void OnLoaded({KVObjectType} data);\n"));
        source.Append("}\n");

        return new Result(hintName, source.ToString(), diagnostics.ToImmutable());
    }

    private static bool IsAutoProperty(PropertyDeclarationSyntax property)
        => property.ExpressionBody == null
            && property.AccessorList != null
            && property.AccessorList.Accessors.All(static accessor => accessor.Body == null && accessor.ExpressionBody == null);

    private static bool HasAttribute(ISymbol symbol, string attributeName)
        => symbol.GetAttributes().Any(attribute => attribute.AttributeClass?.ToDisplayString() == attributeName);

    private static string GetKey(IPropertySymbol property)
    {
        var attribute = property.GetAttributes().FirstOrDefault(static attribute => attribute.AttributeClass?.ToDisplayString() == PropertyAttributeName);

        return attribute != null && attribute.ConstructorArguments.Length == 1 && attribute.ConstructorArguments[0].Value is string key
            ? key
            : DefaultKey(property.Name, property.Type);
    }

    /// <summary>
    /// The key a property is read from without <c>[KVProperty]</c>: <c>m_</c>, a type prefix (<c>b</c> for
    /// bools, <c>fl</c> for floating point, <c>n</c> for integers) and the property name, which starts
    /// lowercase after an empty prefix unless it begins with an acronym.
    /// </summary>
    public static string DefaultKey(string propertyName, ITypeSymbol type)
    {
        var prefix = type.SpecialType switch
        {
            SpecialType.System_Boolean => "b",
            SpecialType.System_Single or SpecialType.System_Double => "fl",
            SpecialType.System_Byte or SpecialType.System_SByte or SpecialType.System_Int16 or SpecialType.System_UInt16
                or SpecialType.System_Int32 or SpecialType.System_UInt32 or SpecialType.System_Int64 or SpecialType.System_UInt64 => "n",
            _ => string.Empty,
        };

        if (prefix.Length > 0 || propertyName.Length == 0 || (propertyName.Length > 1 && char.IsUpper(propertyName[1])))
        {
            return "m_" + prefix + propertyName;
        }

        return "m_" + char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1);
    }

    // A format string with {0} standing for the key literal, or null when the type is not supported
    private static string? ReadExpression(ITypeSymbol type)
    {
        switch (type.SpecialType)
        {
            case SpecialType.System_Boolean: return "data.GetProperty<bool>({0})";
            case SpecialType.System_String: return "data.GetProperty<string>({0})";
            case SpecialType.System_Byte: return "data.GetByteProperty({0})";
            case SpecialType.System_SByte: return "(sbyte)data.GetIntegerProperty({0})";
            case SpecialType.System_Int16: return "data.GetInt16Property({0})";
            case SpecialType.System_UInt16: return "(ushort)data.GetIntegerProperty({0})";
            case SpecialType.System_Int32: return "data.GetInt32Property({0})";
            case SpecialType.System_UInt32: return "data.GetUInt32Property({0})";
            case SpecialType.System_Int64: return "data.GetIntegerProperty({0})";
            case SpecialType.System_UInt64: return "data.GetUnsignedIntegerProperty({0})";
            case SpecialType.System_Single: return "data.GetFloatProperty({0})";
            case SpecialType.System_Double: return "data.GetDoubleProperty({0})";
        }

        if (type.TypeKind == TypeKind.Enum)
        {
            return $"data.GetEnumValue<{FullName(type)}>({{0}})";
        }

        if (type is IArrayTypeSymbol array)
        {
            return ArrayReadExpression(array.ElementType);
        }

        return type.ToDisplayString() switch
        {
            KVObjectName => $"data.GetProperty<{KVObjectType}>({{0}})",
            "System.Numerics.Vector2" => "data.GetSubCollection({0}).ToVector2()",
            "System.Numerics.Vector3" => "data.GetSubCollection({0}).ToVector3()",
            "System.Numerics.Vector4" => "data.GetSubCollection({0}).ToVector4()",
            "System.Numerics.Quaternion" => "data.GetSubCollection({0}).ToQuaternion()",
            "ValveResourceFormat.Renderer.GlobalSymbol" => "data.GetProperty<string>({0})",
            "ValveResourceFormat.ResourceTypes.ModelAnimation.FrameBone" => "data.GetTransformProperty({0})",
            "ValveResourceFormat.Particles.Utils.PiecewiseCurve" => $"new {FullName(type)}(data.GetProperty<{KVObjectType}>({{0}}), false)",
            _ => HasDataConstructor(type) ? $"new {FullName(type)}(data.GetProperty<{KVObjectType}>({{0}}))" : null,
        };
    }

    private static string? ArrayReadExpression(ITypeSymbol element)
    {
        if (element.TypeKind == TypeKind.Enum)
        {
            return null;
        }

        switch (element.ToDisplayString())
        {
            case "ValveResourceFormat.Renderer.GlobalSymbol": return "data.GetSymbolArray({0})";
            case "ValveResourceFormat.ResourceTypes.ModelAnimation.FrameBone": return "data.GetTransformArray({0})";
            case "float": return "data.GetFloatArray({0})";
            case "System.Numerics.Vector2": return VectorArray("ToVector2");
            case "System.Numerics.Vector3": return VectorArray("ToVector3");
            case "System.Numerics.Vector4": return VectorArray("ToVector4");
            case "System.Numerics.Quaternion": return VectorArray("ToQuaternion");
        }

        if (HasDataConstructor(element))
        {
            return $"[.. global::System.Linq.Enumerable.Select(data.GetArray<{KVObjectType}>({{0}}) ?? [], kv => new {FullName(element)}(kv))]";
        }

        return $"data.GetArray<{FullName(element)}>({{0}}) ?? []";
    }

    // Vectors are stored as arrays of numbers, so a vector array is an array of those
    private static string VectorArray(string conversion)
        => $"[.. global::System.Linq.Enumerable.Select(data.GetArray<{KVObjectType}>({{0}}) ?? [], value => value.{conversion}())]";

    // Transfer types and types with a constructor taking only the data
    private static bool HasDataConstructor(ITypeSymbol? type)
    {
        if (type is not INamedTypeSymbol named || named.SpecialType == SpecialType.System_Object)
        {
            return false;
        }

        if (HasAttribute(named, TransferAttributeName))
        {
            return true;
        }

        return named.InstanceConstructors.Any(static constructor =>
            constructor.DeclaredAccessibility != Accessibility.Private
            && constructor.Parameters.Length == 1
            && constructor.Parameters[0].Type.ToDisplayString() == KVObjectName);
    }

    private static string FullName(ITypeSymbol type) => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static string Literal(string value) => "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
