// <auto-generated/>
// Make stylecop ignore this file because we're rewriting KV3 in separate project.
using System;

namespace ValveResourceFormat.KeyValues
{
    public enum KVFlag
    {
        None,
        Resource,
        DeferredResource
    }

    public class KVFlaggedValue : KVValue
    {
        public KVFlag Flag { get; private set; }

        public KVFlaggedValue(KVType type, object value)
            : base(type, value)
        {
            Flag = KVFlag.None;
        }

        public KVFlaggedValue(KVType type, KVFlag flag, object value)
            : base(type, value)
        {
            Flag = flag;
        }
    }
}
