// <auto-generated/>
// Make stylecop ignore this file because we're rewriting KV3 in separate project.
using System;

namespace ValveResourceFormat.KeyValues
{
    /// <summary>
    /// Class to hold type + value
    /// </summary>
    public class KVValue
    {
        public KVType Type { get; private set; }
        public object Value { get; private set; }

        public KVValue(KVType type, object value)
        {
            Type = type;
            Value = value;
        }
    }
}
