<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RollForward>LatestMajor</RollForward>
    <OutputType>Exe</OutputType>
    <PublishReadyToRun>false</PublishReadyToRun>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.73.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ValveResourceFormat\ValveResourceFormat.csproj" />
    <ProjectReference Include="..\Renderer\Renderer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Files\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
