#!/bin/sh

if ! type dotnet > /dev/null; then
    echo You need to install .NET Core from https://dot.net
    exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

dotnet "$DIR/Decompiler.dll" "$@"
exit $?
