name: Bug Report
description: File a bug report
labels: [Bug]
type: 'Bug'
body:
- type: textarea
  id: description
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true

- type: textarea
  id: expected
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true

- type: textarea
  id: logs
  attributes:
    label: Relevant log output or exception with stacktrace
    description: "Copy and paste any relevant log output. *This will be automatically formatted into code, backticks are not needed.*"
    placeholder: "System.IndexOutOfRangeException: Index was outside the bounds of the array…"
    render: shell

- type: input
  id: game
  attributes:
    label: What game does this happen in
  validations:
    required: true

- type: textarea
  id: file
  attributes:
    label: Reference file in a Source 2 game
    description: Provide path to the file that causes this behavior. If this happens in a workshop item, include a link to the workshop.
  validations:
    required: true

- type: input
  id: version
  attributes:
    label: What version of S2V are you using?
    description: |
      # **Make sure your issue still exists on [the latest dev build.](https://valveresourceformat.github.io/)** (NOT RELEASE)
    placeholder: Use copy version button in the about window. Download dev build from the site (NOT RELEASE)
  validations:
    required: true

- type: dropdown
  attributes:
    label: Have you tried the latest dev build?
    description: "**Make sure your issue still exists on [the latest dev build.](https://valveresourceformat.github.io/)**"
    options:
      - "I don't know what this means"
      - "No"
      - "Yes"
  validations:
    required: true
