name: Bug Report
description: File a bug report
labels: [bug]
body:
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true

- type: textarea
  id: logs
  attributes:
    label: Relevant log output or exception with stacktrace
    description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    render: shell

- type: input
  attributes:
    label: What game does this happen in
    placeholder: "Dota 2"
  validations:
    required: true

- type: textarea
  attributes:
    label: Reference file in a Source 2 game
    description: Give a filename (and path to it) that causes this behavior.
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true

- type: input
  attributes:
    label: What version of VRF are you using? On what platform?
    description: Before creating an issue, make sure it still exists on the latest dev build. You can get version from Console tab.
  validations:
    required: true
