namespace ValveResourceFormat.CompiledShader;

public enum RenderState
{
    FillMode = 0,
    CullMode = 1,
    DepthBias = 2,
    DepthBiasClamp = 4,
    SlopeScaleDepthBias = 3,
    DepthClipEnable = 13,
    MultisampleEnable = 14,
    SampleMask = 15,
    DepthEnable = 16,
    DepthWriteEnable = 17,
    DepthFunc = 18,
    StencilEnable = 21,
    StencilReadMask = 22,
    StencilWriteMask = 23,
    StencilFailOp = 24,
    StencilDepthFailOp = 25,
    StencilPassOp = 26,
    StencilFunc = 27,
    BackStencilFailOp = 28,
    BackStencilDepthFailOp = 29,
    BackStencilPassOp = 30,
    BackStencilFunc = 31,
    StencilRef = 32,
    AlphaToCoverageEnable = 37,

    BlendEnable = 41,
    IndependentBlendEnable = 42,
    SrcBlend = 43,
    DstBlend = 44,
    BlendOp = 45,
    SrcBlendAlpha = 46,
    DstBlendAlpha = 47,
    BlendOpAlpha = 48,
    ColorWriteEnable0 = 49,
    ColorWriteEnable1 = 50,
    ColorWriteEnable2 = 51,
    ColorWriteEnable3 = 52,
    SrgbWriteEnable0 = 53,
    SrgbWriteEnable1 = 54,
    SrgbWriteEnable2 = 55,
    SrgbWriteEnable3 = 56,
    BlendFactor = 57,
    HighPrecisionBlendEnable = 58,
    AlphaTestEnable = 59,
    AlphaTestRef = 60,
    AlphaTestFunc = 61,
}
