namespace ValveResourceFormat
{
    /// <summary>
    /// Entity field data types.
    /// </summary>
    public enum EntityFieldType
    {
#pragma warning disable CS1591
        Void = 0x0,
        Float = 0x1,
        String = 0x2,
        Vector = 0x3,
        Quaternion = 0x4,
        Integer = 0x5,
        Boolean = 0x6,
        Short = 0x7,
        Character = 0x8,
        Color32 = 0x9,
        Embedded = 0xa,
        Custom = 0xb,
        ClassPtr = 0xc,
        EHandle = 0xd,
        PositionVector = 0xe,
        Time = 0xf,
        Tick = 0x10,
        SoundName = 0x11,
        Input = 0x12,
        Function = 0x13,
        VMatrix = 0x14,
        VMatrixWorldspace = 0x15,
        Matrix3x4Worldspace = 0x16,
        Interval = 0x17,
        Unused = 0x18,
        Vector2d = 0x19,
        Integer64 = 0x1a,
        Vector4D = 0x1b,
        Resource = 0x1c,
        TypeUnknown = 0x1d,
        CString = 0x1e,
        HScript = 0x1f,
        Variant = 0x20,
        UInt64 = 0x21,
        Float64 = 0x22,
        PositiveIntegerOrNull = 0x23,
        HScriptNewInstance = 0x24,
        UInt = 0x25,
        UtlStringToken = 0x26,
        QAngle = 0x27,
        NetworkOriginCellQuantizedVector = 0x28,
        HMaterial = 0x29,
        HModel = 0x2a,
        NetworkQuantizedVector = 0x2b,
        NetworkQuantizedFloat = 0x2c,
        DirectionVectorWorldspace = 0x2d,
        QAngleWorldspace = 0x2e,
        QuaternionWorldspace = 0x2f,
        HScriptLightbinding = 0x30,
        V8_value = 0x31,
        V8_object = 0x32,
        V8_array = 0x33,
        V8_callback_info = 0x34,
        UtlString = 0x35,
        NetworkOriginCellQuantizedPositionVector = 0x36,
        HRenderTexture = 0x37,
        HParticleSystemDefinition = 0x38,
        UInt8 = 0x39,
        UInt16 = 0x3a,
        CTransform = 0x3b,
        CTransformWorldspace = 0x3c,
        HPostProcessing = 0x3d,
        Matrix3x4 = 0x3e,
        Shim = 0x3f,
        CMotionTransform = 0x40,
        CMotionTransformWorldspace = 0x41,
        AttachmentHandle = 0x42,
        AmmoIndex = 0x43,
        ConditionId = 0x44,
        AiScheduleBits = 0x45,
        ModifierHandle = 0x46,
        RotationVector = 0x47,
        RotationVectorWorldspace = 0x48,
        HvData = 0x49,
        Scale32 = 0x4a,
        StringAndToken = 0x4b,
        EngineTime = 0x4c,
        EngineTick = 0x4d,
        WorldGroupId = 0x4e,
        GlobalSymbol = 0x4f,
#pragma warning restore CS1591
    }
}
