namespace ValveResourceFormat
{
    // used for particles
    public enum VectorFloatExpressionType
    {
        VECTOR_FLOAT_EXPRESSION_UNINITIALIZED,
        VECTOR_FLOAT_EXPRESSION_DOTPRODUCT,
        VECTOR_FLOAT_EXPRESSION_DISTANCE,
        VECTOR_FLOAT_EXPRESSION_DISTANCESQR,
        VECTOR_FLOAT_EXPRESSION_INPUT1_LENGTH,
        VECTOR_FLOAT_EXPRESSION_INPUT1_LENGTHSQR,
        VECTOR_FLOAT_EXPRESSION_INPUT1_NOISE,
    }
}
