using System.Globalization;
using System.IO;
using System.Linq;
using ValveKeyValue;
using ValveResourceFormat.ResourceTypes;
using ValveResourceFormat.Serialization.KeyValues;
using static ValveResourceFormat.IO.KVHelpers;

namespace ValveResourceFormat.IO;

/// <summary>
/// Rebuilds the model doc nodes behind a model's authored key values: the gameplay data classes it
/// carries, its foot and break markup, and the references it holds to other resources.
/// </summary>
partial class ModelExtract
{
    /// <summary>
    /// Rebuilds the nodes a model doc carries for its authored key values. The resource references are
    /// written for every model, the rest only for a model that kept its key values.
    /// </summary>
    private void ExtractModelKeyValues(Model model, ModelDocLists lists, KVObject rootNode)
    {
        AddResourceReferenceNodes(model, lists);

        var keyvalues = model.KeyValues;

        if (keyvalues.Count == 0)
        {
            return;
        }

        AddRigNodes(model, keyvalues, lists, rootNode);
        AddGameDataNodes(keyvalues, lists, GetMarkedUpPhysicsBodies());
        AddStickerAndKeychainNodes(keyvalues, lists);
    }

    /// <summary>
    /// Writes the references a model holds to other resources: the models it includes animations from,
    /// the material attributes its animations drive, its NM skeletons and its animation graphs.
    /// </summary>
    private static void AddResourceReferenceNodes(Model model, ModelDocLists lists)
    {
        if (model.Data.ContainsKey("m_refAnimIncludeModels"))
        {
            foreach (var animIncludeModel in model.Data.GetArray<string>("m_refAnimIncludeModels")!)
            {
                lists.Animations.Add(MakeNode("AnimIncludeModel", ("model", animIncludeModel)));
            }
        }

        foreach (var (attributeName, numChannels) in model.GetAnimatedMaterialAttributes())
        {
            if (numChannels == 1)
            {
                lists.Animations.Add(MakeNode("AnimatedMaterialAttributeValue",
                    ("material_attribute_name", attributeName),
                    ("target_value", 0f)
                ));
            }
            else
            {
                lists.Animations.Add(MakeNode("AnimatedMaterialAttributeColor",
                    ("material_attribute_name", attributeName),
                    ("target_color", MakeArray(255f, 255f, 255f, 255f))
                ));
            }
        }

        foreach (var skeletonRef in model.NmSkeletonRefs)
        {
            lists.NmSkeletons.Add(MakeNode("NmSkeletonReference", ("filename", skeletonRef)));
        }

        foreach (var (identifier, graphPath) in model.AnimGraph2References)
        {
            // The default graph is the reference without an identifier.
            lists.AnimGraph2.Add(string.IsNullOrEmpty(identifier)
                ? MakeNode("DefaultAnimGraph2", ("filename", graphPath))
                : MakeNode("AnimGraph2", ("name", identifier), ("filename", graphPath)));
        }
    }

    /// <summary>
    /// Writes the gameplay data classes a model carries, plus its look-at, movement, feet and break
    /// markup, each of which the compiler folds into key values under its own name.
    /// </summary>
    private static void AddGameDataNodes(KVObject keyvalues, ModelDocLists lists, HashSet<string> markedUpPhysicsBodies)
    {
        var genericDataClasses = new string[] {
            "prop_data",
            "character_arm_config",
            "vr_carry_type",
            "door_sounds",
            "nav_data",
            "npc_foot_sweep",
            "ai_model_info",
            "breakable_door_model",
            "dynamic_interactions",
            "explosion_behavior",
            "eye_occlusion_renderer",
            "fire_interactions",
            "gastank_markup",
            "hand_conform_data",
            "handpose_data",
            "physgun_interactions",
            "weapon_metadata",
            "glove_viewmodel_reference",
            "composite_material_order",
            "patch_camera_preset_list",
            "camera_settings",
            "scene_data_map",
            "particle_settings",
            "damage_number_settings",
            "CitadelCameraSettings_t",
            "CCitadelHeroModelGameData_t",
            "CCitadelNPCModelGameData_t",
            "CitadelUnitStatusSettings_t",
            "CitadelModelDamageNumberSettings_t",
            "CitadelModelParticleSettings_t",
            "TaggedSoundSettings_t",
            "CitadelModelSceneData_t",
            "CitadelMuzzleSettings_t",
            "CitadelTeamRelativeParticleSettings_t",
            "CitadelEventIDToBodyGroupMapping_t",
            //"AttachmentCameraData", - is autogenerated from AttachmentCameraPreview/ExporttoRuntimeModel modeldoc node/parameter
            "CDestructiblePart",
            "CDestructiblePartsSystemData",
            "DeformablePropModelGameData_t",
            "CPhysicsBodyGameMarkupData",
            "electrical_interactions",
            "world_interactions",
            "door_options",
            "hand_pose_pair",
            "keychain_inspect",
            "muzzle_desc",
            "unit_status_settings",
            "cloth_ground_plane",
            "CitadelUnitQuerySettings_t",
            "CCitadelDropShadowData_t",
        };

        var genericDataClassesList = new (string ListKey, string Class)[] {
        ("ao_proxy_capsule_list", "ao_proxy_capsule"),
        ("ao_proxy_box_list", "ao_proxy_box"),
        ("particles_list", "particle"),
        ("hand_pose_list", "hand_pose_pair"),
        ("eye_data_list", "eye"),
        ("bodygroup_driven_morph_list", "bodygroup_driven_morph"),
        ("materialgroup_driven_morph_list", "materialgroup_driven_morph"),
        ("animating_breakable_stage_list", "animating_breakable_stage"),
        ("cables_list", "cable"),
        ("high_quality_shadows_region_list", "high_quality_shadows_region"),
        ("particle_cfg_list", "particle_cfg"),
        ("snapshot_weights_upperbody_list", "snapshot_weights_upperbody"),
        ("snapshot_weights_all_list", "snapshot_weights_all"),
        ("bodygroup_preset_list", "bodygroup_preset"),
        ("muzzle_desc_list", "muzzle_settings"),
        ("unit_status_settings_list", "unit_status_settings"),
        ("team_relative_particles_cfg_list", "team_relative_particle_settings"),
        ("CNPCPhysicsHull", "CNPCPhysicsHull"), // exports as list, needs m_sName changed to name near game_class
    };

        foreach (var genericDataClass in genericDataClasses)
        {
            if (!keyvalues.ContainsKey(genericDataClass))
            {
                continue;
            }

            if (genericDataClass == "CPhysicsBodyGameMarkupData")
            {
                AddPhysicsBodyGameData(lists, keyvalues.GetSubCollection(genericDataClass), markedUpPhysicsBodies);
                continue;
            }

            // Some of these classes hold one entry and others an array; an array wrapped in a single
            // node compiles back to an unnamed member.
            if (keyvalues[genericDataClass].ValueType == KVValueType.Array)
            {
                foreach (var entry in keyvalues.GetArray(genericDataClass))
                {
                    AddGenericGameData(lists.GameData, genericDataClass, entry);
                }

                continue;
            }

            var genericData = keyvalues.GetSubCollection(genericDataClass);
            if (genericData != null)
            {
                AddGenericGameData(lists.GameData, genericDataClass, genericData);
            }
        }

        foreach (var genericDataClass in genericDataClassesList)
        {
            var dataKey = genericDataClass.ListKey;
            if (keyvalues.GetArray(dataKey) is { } genericDataList)
            {
                foreach (var genericData in genericDataList)
                {
                    AddGenericGameData(lists.GameData, genericDataClass.Class, genericData);
                }
            }
            else if (keyvalues.GetSubCollection(dataKey) is { } singleGenericData)
            {
                // Some models author this as a single KV object instead of a one-element list.
                AddGenericGameData(lists.GameData, genericDataClass.Class, singleGenericData);
            }
        }

        if (keyvalues.GetSubCollection("chicken_metadata") is { } chickenMetadata)
        {
            AddGenericGameData(lists.GameData, "chicken_metadata", chickenMetadata)?.Add("disabled", true);
        }

        if (keyvalues.ContainsKey("LookAtList"))
        {
            var lookAtList = keyvalues.GetSubCollection("LookAtList");
            foreach (var (_, item) in lookAtList)
            {
                if (item.ValueType == KVValueType.Collection)
                {
                    AddGenericGameData(lists.GameData, "LookAtChain", item, "lookat_chain");
                }
            }
        }

        if (keyvalues.ContainsKey("MovementSettings"))
        {
            var movementSettings = keyvalues.GetSubCollection("MovementSettings");
            AddGenericGameData(lists.GameData, "MovementSettings", movementSettings, "movementsettings");
        }

        if (keyvalues.ContainsKey("FeetSettings"))
        {
            var feetSettings = keyvalues.GetSubCollection("FeetSettings");
            var feetNode = ConvertFeetSettings(feetSettings!);
            if (feetNode != null)
            {
                lists.GameData.Add(feetNode);
            }
        }

        if (keyvalues.ContainsKey("break_list"))
        {
            foreach (var breakPiece in keyvalues.GetArray("break_list")!)
            {
                lists.BreakPieces.Add(ConvertBreakPiece(breakPiece));
            }
        }

        if (keyvalues.GetArray("break_command_list") is { } breakCommands)
        {
            foreach (var breakCommand in breakCommands)
            {
                if (ConvertBreakCommand(breakCommand) is { } breakCommandNode)
                {
                    lists.BreakPieces.Add(breakCommandNode);
                }
            }
        }
    }

    /// <summary>
    /// Rebuilds a <c>BreakPieceExternal</c> node from a compiled <c>break_list</c> entry.
    /// </summary>
    /// <remarks>
    /// <c>fademindist</c> and <c>fademaxdist</c> are only written by the legacy break converter and have no node key.
    /// A missing color or material group mode is written as <c>default</c>, because the compiler turns an absent one
    /// into an inherit mode. The legacy <c>ragdoll</c> key names the model of a ragdoll piece. The compiler upgrades a
    /// document of this version by deriving <c>spawn_entity</c> from <c>is_ragdoll</c> and clearing
    /// <c>ragdoll_applies_bind_pose_root</c>, so a ragdoll is written as <c>is_ragdoll</c>.
    /// </remarks>
    private static KVObject ConvertBreakPiece(KVObject breakPiece)
    {
        var node = MakeNode("BreakPieceExternal");
        var inheritOwnerJoints = false;

        foreach (var (key, value) in breakPiece)
        {
            switch (key)
            {
                case "piece_name":
                    node["name"] = value;
                    break;
                case "collision_group_override":
                    node["collision_group"] = value;
                    break;
                case "placementbone":
                    node["placement_mode"] = "bone";
                    node["placement_bone"] = value;
                    break;
                case "placementattachment":
                    node["placement_mode"] = "attachment";
                    node["placement_attach"] = value;
                    break;
                case "inherit_owner_joints":
                    inheritOwnerJoints = value.ToBoolean(CultureInfo.InvariantCulture);
                    break;
                case "ragdoll":
                    node["model"] = value;
                    node["is_ragdoll"] = true;
                    break;
                case "spawn_entity":
                    if (value.ToString(CultureInfo.InvariantCulture) == "ragdoll")
                    {
                        node["is_ragdoll"] = true;
                    }

                    break;
                case "fademindist" or "fademaxdist" or "ragdoll_applies_bind_pose_root":
                    break;
                default:
                    node[key] = value;
                    break;
            }
        }

        if (inheritOwnerJoints && !node.ContainsKey("physics_joint_modification_type"))
        {
            node.Add("physics_joint_modification_type", "inherit_all_joints");
        }

        foreach (var mode in (ReadOnlySpan<string>)["render_color_mode", "material_group_mode"])
        {
            if (!node.ContainsKey(mode))
            {
                node.Add(mode, "default");
            }
        }

        return node;
    }

    /// <summary>
    /// Rebuilds a <c>BreakCommand</c> node from a compiled <c>break_command_list</c> entry, whose command name is the
    /// node's game class and whose other keys pass through. Returns <see langword="null"/> for an entry without a
    /// command name.
    /// </summary>
    private static KVObject? ConvertBreakCommand(KVObject breakCommand)
    {
        if (breakCommand.GetStringProperty("break_command") is not { } gameClass)
        {
            return null;
        }

        var gameKeys = KVObject.Collection();

        foreach (var (key, value) in breakCommand)
        {
            if (key != "break_command")
            {
                gameKeys.Add(key, value);
            }
        }

        return MakeNode("BreakCommand",
            ("game_class", gameClass),
            ("game_keys", gameKeys)
        );
    }

    static KVObject? ConvertFeetSettings(KVObject feetSettings)
    {
        var children = KVObject.Array();

        // Field mappings from compiled to source names
        var footFieldMappings = new (string CompiledName, string SourceName)[]
        {
            ("m_name", "name"),
            ("m_ankleBoneName", "anklebone"),
            ("m_toeBoneName", "toebone"),
            ("m_vBallOffset", "balloffset"),
            ("m_vHeelOffset", "heeloffset"),
            ("m_flTraceHeight", "traceheight"),
            ("m_flTraceRadius", "traceradius"),
        };

        foreach (var (_, footEntry) in feetSettings.Children)
        {
            if (footEntry.ValueType != KVValueType.Collection)
            {
                continue;
            }

            var footNode = MakeNode("Foot");

            // Map compiled field names to source field names
            foreach (var (compiledName, sourceName) in footFieldMappings)
            {
                if (footEntry.ContainsKey(compiledName))
                {
                    footNode.Add(sourceName, footEntry[compiledName]);
                }
            }

            // autolevel is typically true by default in source format
            footNode.Add("autolevel", true);

            children.Add(footNode);
        }

        if (children.Count == 0)
        {
            return null;
        }

        var feetNode = MakeNode("Feet", ("children", children));

        // Parent-level field mappings
        var parentFieldMappings = new (string CompiledName, string SourceName)[]
        {
            ("m_flLockTolerance", "locktolerance"),
            ("m_flHeightTolerance", "heighttolerance"),
            ("m_bSanitizeTrajectories", "sanitizetrajectories"),
        };

        // Add parent-level properties if they exist
        foreach (var (compiledName, sourceName) in parentFieldMappings)
        {
            if (feetSettings.ContainsKey(compiledName))
            {
                feetNode.Add(sourceName, feetSettings[compiledName]);
            }
        }

        return feetNode;
    }

    static KVObject? AddGenericGameData(KVObject gameDataList, string genericDataClass, KVObject? genericData, string? dataKey = null)
    {
        if (genericData is null)
        {
            return null;
        }

        // Remove quotes from keys by rebuilding the object
        var cleanedData = KVObject.Collection();
        foreach (var (key, value) in genericData.Children)
        {
            var trimmed = key?.Trim('"') ?? string.Empty;
            cleanedData.Add(trimmed, value);
        }

        var name = cleanedData.GetStringProperty("name", string.Empty);

        // The node name should not contain non identifier characters like / or .
        name = Path.GetFileNameWithoutExtension(name);

        KVObject genericGameData;
        if (dataKey == null)
        {
            genericGameData = MakeNode("GenericGameData",
                ("name", name),
                ("game_class", genericDataClass),
                ("game_keys", cleanedData)
            );
        }
        else
        {
            genericGameData = MakeNode(genericDataClass,
                ("name", name),
                (dataKey, cleanedData)
            );
        }

        gameDataList.Add(genericGameData);
        return genericGameData;
    }
}
