namespace GUI.Types.ParticleRenderer
{
    public enum ParticleBlendMode
    {
        PARTICLE_OUTPUT_BLEND_MODE_ALPHA = 0,
        PARTICLE_OUTPUT_BLEND_MODE_ADD = 1,
        PARTICLE_OUTPUT_BLEND_MODE_BLEND_ADD = 2,
        PARTICLE_OUTPUT_BLEND_MODE_HALF_BLEND_ADD = 3,
        PARTICLE_OUTPUT_BLEND_MODE_NEG_HALF_BLEND_ADD = 4,
        PARTICLE_OUTPUT_BLEND_MODE_MOD2X = 5,
        PARTICLE_OUTPUT_BLEND_MODE_LIGHTEN = 6,
    }
}
