using System;
using System.Numerics;

namespace GUI.Utils;

static class HammerEntities
{
    public class HammerEntity
    {
        public string[] Icons = Array.Empty<string>();
        public Vector3 Color;
    }

    public static HammerEntity Get(string classname)
    {
        return classname switch
        {
            "ai_attached_item_manager" => new() { Icons = new[] { "materials/editor/ai_attached_item_manager.vmat", "materials/editor/info_target.vmat" } },
            "ai_battle_line" => new() { Icons = new[] { "models/pigeon.vmdl" } },
            "ai_goal_fightfromcover" => new() { Icons = new[] { "materials/editor/ai_goal_follow.vmat" } },
            "ai_goal_follow" => new() { Icons = new[] { "materials/editor/ai_goal_follow.vmat" } },
            "ai_goal_injured_follow" => new() { Icons = new[] { "materials/editor/ai_goal_follow.vmat" } },
            "ai_goal_lead" => new() { Icons = new[] { "materials/editor/ai_goal_lead.vmat" } },
            "ai_goal_lead_weapon" => new() { Icons = new[] { "materials/editor/ai_goal_lead.vmat" } },
            "ai_goal_police" => new() { Icons = new[] { "materials/editor/ai_goal_police.vmat" } },
            "ai_goal_standoff" => new() { Icons = new[] { "materials/editor/ai_goal_standoff.vmat" } },
            "ai_relationship" => new() { Icons = new[] { "materials/editor/ai_relationship.vmat" } },
            "ai_scripted_abilityusage" => new() { Icons = new[] { "materials/editor/aiscripted_schedule.vmat" }, Color = new Vector3(255, 0, 255) },
            "ai_scripted_idle" => new() { Icons = new[] { "materials/editor/aiscripted_schedule.vmat" }, Color = new Vector3(255, 0, 255) },
            "ai_scripted_moveto" => new() { Icons = new[] { "materials/editor/ai_scripted_moveto.vmat" }, Color = new Vector3(255, 0, 255) },
            "ai_sound" => new() { Icons = new[] { "materials/editor/ai_sound.vmat" } },
            "aiscripted_schedule" => new() { Icons = new[] { "materials/editor/aiscripted_schedule.vmat" }, Color = new Vector3(255, 0, 255) },
            "ambient_generic" => new() { Icons = new[] { "materials/editor/ambient_generic.vmat" } },
            "assault_assaultpoint" => new() { Icons = new[] { "materials/editor/assault_point.vmat" } },
            "assault_rallypoint" => new() { Icons = new[] { "materials/editor/assault_rally.vmat" } },
            "beam_spotlight" => new() { Icons = new[] { "models/editor/cone_helper.vmdl" } },
            "color_correction" => new() { Icons = new[] { "materials/editor/color_correction.vmat" } },
            "combine_attached_armor_prop" => new() { Icons = new[] { "models/characters/combine_soldier_heavy/combine_hand_shield.vmdl" } },
            "combine_mine" => new() { Icons = new[] { "models/props_combine/combine_mine/combine_mine.vmdl" } },
            "commentary_auto" => new() { Icons = new[] { "materials/editor/commentary_auto.vmat" } },
            "counterterrorist_team_intro" => new() { Icons = new[] { "models/editor/counterterrorist_team_intro.vmdl" } },
            "csm_fov_override" => new() { Icons = new[] { "models/editor/camera.vmdl" } },
            "devtest_hierarchy2" => new() { Icons = new[] { "models/survivors/survivor_gambler.vmdl" } },
            "dota_color_correction" => new() { Icons = new[] { "materials/editor/color_correction.vmat" } },
            "dota_world_particle_system" => new() { Icons = new[] { "models/editor/cone_helper.vmdl" } },
            "end_of_match" => new() { Icons = new[] { "models/editor/end_of_match.vmdl" } },
            "env_alyxemp" => new() { Color = new Vector3(0, 0, 255) },
            "env_blood" => new() { Color = new Vector3(255, 0, 0) },
            "env_clock" => new() { Icons = new[] { "materials/editor/logic_timer.vmat" } },
            "env_combined_light_probe_volume" => new() { Icons = new[] { "models/editor/env_cubemap.vmdl" } },
            "env_cubemap" => new() { Icons = new[] { "models/editor/env_cubemap.vmdl" } },
            "env_cubemap_box" => new() { Icons = new[] { "models/editor/env_cubemap.vmdl" } },
            "env_cubemap_fog" => new() { Icons = new[] { "materials/editor/env_cubemap_fog.vmat" } },
            "env_decal" => new() { Icons = new[] { "models/editor/axis_helper_thick.vmdl" } },
            "env_deferred_spot_light" => new() { Icons = new[] { "models/editor/spot.vmdl" } },
            "env_deferred_spot_light_client_only" => new() { Icons = new[] { "models/editor/spot.vmdl" } },
            "env_dof_controller" => new() { Icons = new[] { "materials/editor/env_dof_controller.vmat" } },
            "env_entity_igniter" => new() { Color = new Vector3(0, 180, 0) },
            "env_explosion" => new() { Icons = new[] { "materials/editor/env_explosion.vmat" } },
            "env_fade" => new() { Icons = new[] { "materials/editor/env_fade.vmat" } },
            "env_fire" => new() { Icons = new[] { "materials/editor/env_fire.vmat" }, Color = new Vector3(0, 180, 0) },
            "env_firesensor" => new() { Color = new Vector3(255, 255, 0) },
            "env_firesource" => new() { Icons = new[] { "materials/editor/env_firesource.vmat" }, Color = new Vector3(255, 255, 0) },
            "env_fog_controller" => new() { Icons = new[] { "materials/editor/env_fog_controller.vmat" }, Color = new Vector3(255, 255, 255) },
            "env_global_light" => new() { Icons = new[] { "models/editor/spot.vmdl" } },
            "env_gradient_fog" => new() { Icons = new[] { "materials/editor/env_fog_controller.vmat" } },
            "env_headcrabcanister" => new() { Icons = new[] { "models/props_combine/headcrabcannister01b.vmdl" } },
            "env_instructor_hint" => new() { Icons = new[] { "materials/editor/env_instructor_hint.vmat" } },
            "env_instructor_vr_hint" => new() { Icons = new[] { "materials/editor/env_instructor_hint.vmat" } },
            "env_light_probe_volume" => new() { Icons = new[] { "models/editor/iv_helper.vmdl" } },
            "env_lightglow" => new() { Icons = new[] { "models/editor/axis_helper_thick.vmdl" }, Color = new Vector3(255, 128, 0) },
            "env_line_occluder" => new() { Color = new Vector3(255, 0, 0) },
            "env_microphone" => new() { Icons = new[] { "materials/editor/env_microphone.vmat" }, Color = new Vector3(0, 0, 255) },
            "env_occluder" => new() { Color = new Vector3(255, 0, 0) },
            "env_particle_glow" => new() { Icons = new[] { "models/editor/cone_helper_xyz.vmdl" } },
            "env_particlelight" => new() { Color = new Vector3(180, 10, 180) },
            "env_physexplosion" => new() { Icons = new[] { "materials/editor/env_physexplosion.vmat" } },
            "env_physimpact" => new() { Icons = new[] { "materials/editor/env_physexplosion.vmat" } },
            "env_player_visibility" => new() { Icons = new[] { "materials/editor/env_player_visibility.vmat" } },
            "env_projectedtexture" => new() { Icons = new[] { "models/editor/spot.vmdl" } },
            "env_rotorshooter" => new() { Icons = new[] { "materials/editor/env_shooter.vmat" } },
            "env_shake" => new() { Icons = new[] { "materials/editor/env_shake.vmat" } },
            "env_shooter" => new() { Icons = new[] { "materials/editor/env_shooter.vmat" } },
            "env_sky" => new() { Icons = new[] { "materials/editor/env_sky.vmat" } },
            "env_smokestack" => new() { Color = new Vector3(255, 255, 255) },
            "env_smoketrail" => new() { Color = new Vector3(200, 50, 0) },
            "env_soundscape" => new() { Icons = new[] { "materials/editor/env_soundscape.vmat" } },
            "env_soundscape_proxy" => new() { Icons = new[] { "materials/editor/env_soundscape.vmat" } },
            "env_soundscape_triggerable" => new() { Icons = new[] { "materials/editor/env_soundscape.vmat" } },
            "env_spark" => new() { Icons = new[] { "materials/editor/env_spark.vmat" } },
            "env_speaker" => new() { Icons = new[] { "materials/editor/ambient_generic.vmat" } },
            "env_spherical_vignette" => new() { Icons = new[] { "materials/editor/env_fog_controller.vmat" } },
            "env_sprite" => new() { Color = new Vector3(20, 140, 20) },
            "env_sun" => new() { Icons = new[] { "materials/editor/env_sun.vmat", "models/editor/light_environment.vmdl" }, Color = new Vector3(255, 255, 255) },
            "env_texturetoggle" => new() { Icons = new[] { "materials/editor/env_texturetoggle.vmat" } },
            "env_tilt" => new() { Icons = new[] { "models/editor/axis_helper_thick.vmdl" } },
            "env_time_of_day" => new() { Icons = new[] { "models/editor/sky_helper.vmdl" } },
            "env_tonemap_controller" => new() { Icons = new[] { "materials/editor/env_tonemap_controller.vmat" } },
            "env_viewer" => new() { Color = new Vector3(0, 255, 0) },
            "env_volumetric_fog_volume" => new() { Icons = new[] { "materials/editor/fog_volume.vmat" } },
            "env_wind" => new() { Icons = new[] { "materials/editor/env_wind.vmat" } },
            "env_wind_clientside" => new() { Icons = new[] { "materials/editor/env_wind.vmat" } },
            "env_world_lighting" => new() { Icons = new[] { "materials/editor/light_env.vmat" } },
            "filter_activator_attribute_int" => new() { Icons = new[] { "materials/editor/filter_class.vmat" } },
            "filter_activator_class" => new() { Icons = new[] { "materials/editor/filter_class.vmat" } },
            "filter_activator_context" => new() { Icons = new[] { "materials/editor/filter_name.vmat" } },
            "filter_activator_mass_greater" => new() { Icons = new[] { "materials/editor/filter_class.vmat" } },
            "filter_activator_model" => new() { Icons = new[] { "materials/editor/filter_model.vmat", "materials/editor/filter_name.vmat" } },
            "filter_activator_name" => new() { Icons = new[] { "materials/editor/filter_name.vmat" } },
            "filter_combineball_type" => new() { Icons = new[] { "materials/editor/filter_class.vmat" } },
            "filter_damage_type" => new() { Icons = new[] { "materials/editor/filter_type.vmat" } },
            "filter_enemy" => new() { Icons = new[] { "materials/editor/filter_class.vmat" } },
            "filter_los" => new() { Icons = new[] { "materials/editor/filter_class.vmat" } },
            "filter_multi" => new() { Icons = new[] { "materials/editor/filter_multiple.vmat" } },
            "filter_proximity" => new() { Icons = new[] { "materials/editor/filter_class.vmat" } },
            "filter_vr_grenade" => new() { Icons = new[] { "materials/editor/filter_name.vmat" } },
            "flashbang_projectile" => new() { Icons = new[] { "models/weapons/w_eq_flashbang_thrown.vmdl" } },
            "func_areaportal" => new() { Color = new Vector3(0, 255, 255) },
            "func_areaportalwindow" => new() { Color = new Vector3(0, 128, 255) },
            "func_ladderendpoint" => new() { Color = new Vector3(127, 127, 127) },
            "func_nav_gen_proj" => new() { Icons = new[] { "models/editor/arrow.vmdl" } },
            "func_survival_c4_target" => new() { Icons = new[] { "models/props_survival/safe/safe.vmdl" } },
            "func_viscluster" => new() { Color = new Vector3(180, 180, 0) },
            "game_end" => new() { Icons = new[] { "materials/editor/game_end.vmat" } },
            "game_text" => new() { Icons = new[] { "materials/editor/game_text.vmat" } },
            "ghost_actor" => new() { Icons = new[] { "materials/editor/ghost_actor.vmat" } },
            "ghost_speaker" => new() { Icons = new[] { "materials/editor/ghost_speaker.vmat" } },
            "gibshooter" => new() { Icons = new[] { "materials/editor/gibshooter.vmat" } },
            "grenade_helicopter" => new() { Icons = new[] { "models/combine_helicopter/helicopter_bomb01.vmdl" } },
            "haptic_relay" => new() { Icons = new[] { "materials/editor/haptic_relay.vmat" } },
            "hegrenade_projectile" => new() { Icons = new[] { "models/weapons/w_eq_fraggrenade.vmdl" } },
            "hl_vr_environmental_interaction" => new() { Icons = new[] { "models/static.vmdl" }, Color = new Vector3(255, 255, 0) },
            "hlvr_grenadepin_proxy" => new() { Icons = new[] { "models/weapons/vr_grenade/vr_grenade_01_pin.vmdl" } },
            "hlvr_piano" => new() { Icons = new[] { "models/props/hotel/piano_001.vmdl" } },
            "hlvr_weapon_energygun" => new() { Icons = new[] { "models/weapons/vr_alyxgun/vr_alyxgun.vmdl" } },
            "hostage_entity" => new() { Icons = new[] { "models/hostage/hostage.vmdl" } },
            "info_armsrace_counterterrorist" => new() { Icons = new[] { "characters/models/ctm_st6/ctm_st6_variantl.vmdl" } },
            "info_armsrace_terrorist" => new() { Icons = new[] { "characters/models/tm_leet/tm_leet_varianta.vmdl" } },
            "info_cull_triangles" => new() { Icons = new[] { "materials/editor/info_cull_triangles.vmat" } },
            "info_deathmatch_spawn" => new() { Icons = new[] { "characters/models/tm_professional/tm_professional_varh.vmdl" } },
            "info_enemy_terrorist_spawn" => new() { Icons = new[] { "characters/models/tm_phoenix/tm_phoenix.vmdl" } },
            "info_hint" => new() { Icons = new[] { "models/editor/node_hint.vmdl" }, Color = new Vector3(255, 255, 255) },
            "info_hlvr_equip_player" => new() { Icons = new[] { "materials/editor/info_hlvr_equip_player.vmat" } },
            "info_hlvr_holo_hacking_plug" => new() { Icons = new[] { "models/props_combine/combine_doors/combine_hacking_interact_point.vmdl" } },
            "info_hlvr_offscreen_particle_texture" => new() { Icons = new[] { "materials/editor/info_hlvr_offscreen_particle_texture.vmat" } },
            "info_hlvr_toner_path" => new() { Icons = new[] { "materials/editor/info_hlvr_toner_path.vmat" } },
            "info_hlvr_toner_port" => new() { Icons = new[] { "models/props_combine/combine_power/power_stake_a.vmdl" } },
            "info_hostage_spawn" => new() { Icons = new[] { "models/hostage/hostage.vmdl" } },
            "info_intermission" => new() { Color = new Vector3(0, 180, 0) },
            "info_ladder_dismount" => new() { Color = new Vector3(255, 128, 255) },
            "info_landmark" => new() { Icons = new[] { "materials/editor/info_landmark.vmat" } },
            "info_lighting" => new() { Icons = new[] { "materials/editor/info_lighting.vmat" } },
            "info_node" => new() { Icons = new[] { "models/editor/ground_node.vmdl" }, Color = new Vector3(232, 219, 8) },
            "info_node_air" => new() { Icons = new[] { "models/editor/air_node.vmdl" }, Color = new Vector3(232, 171, 8) },
            "info_node_air_hint" => new() { Icons = new[] { "models/editor/air_node_hint.vmdl" }, Color = new Vector3(232, 171, 8) },
            "info_node_climb" => new() { Icons = new[] { "models/editor/climb_node.vmdl" }, Color = new Vector3(153, 215, 103) },
            "info_node_hint" => new() { Icons = new[] { "models/editor/ground_node_hint.vmdl" }, Color = new Vector3(232, 219, 8) },
            "info_node_link" => new() { Color = new Vector3(220, 180, 0) },
            "info_notepad" => new() { Icons = new[] { "materials/editor/info_notepad.vmat" } },
            "info_npc_spawn_destination" => new() { Icons = new[] { "materials/editor/info_npc_spawn_destination.vmat", "materials/editor/info_target.vmat" } },
            "info_overlay" => new() { Icons = new[] { "models/editor/overlay_helper.vmdl" }, Color = new Vector3(80, 150, 225) },
            "info_particle_system" => new() { Icons = new[] { "models/editor/cone_helper.vmdl", "models/editor/cone_helper_xyz.vmdl" } },
            "info_particle_target" => new() { Icons = new[] { "models/editor/cone_helper.vmdl" } },
            "info_player_counterterrorist" => new() { Icons = new[] { "characters/models/ctm_sas/ctm_sas.vmdl" } },
            "info_player_start" => new() { Icons = new[] { "models/editor/playerstart.vmdl" } },
            "info_player_start_badguys" => new() { Icons = new[] { "models/editor/playerstart.vmdl" } },
            "info_player_start_dota" => new() { Icons = new[] { "models/editor/playerstart.vmdl" } },
            "info_player_start_goodguys" => new() { Icons = new[] { "models/editor/playerstart.vmdl" } },
            "info_player_terrorist" => new() { Icons = new[] { "characters/models/tm_phoenix/tm_phoenix.vmdl" } },
            "info_projecteddecal" => new() { Icons = new[] { "models/editor/axis_helper_thick.vmdl" } },
            "info_radar_target" => new() { Icons = new[] { "materials/editor/info_target.vmat" } },
            "info_roquelaire_perch" => new() { Icons = new[] { "models/editor/axis_helper.vmdl", "materials/editor/info_target.vmat" } },
            "info_snipertarget" => new() { Icons = new[] { "materials/editor/info_target.vmat" } },
            "info_spawngroup_landmark" => new() { Icons = new[] { "materials/editor/info_target.vmat" } },
            "info_spawngroup_load_unload" => new() { Icons = new[] { "materials/editor/info_target.vmat" }, Color = new Vector3(0, 255, 0) },
            "info_target" => new() { Icons = new[] { "models/editor/info_target.vmdl", "materials/editor/info_target.vmat" } },
            "info_target_advisor_roaming_crash" => new() { Icons = new[] { "materials/editor/info_target.vmat" } },
            "info_target_gunshipcrash" => new() { Icons = new[] { "materials/editor/info_target.vmat" } },
            "info_target_helicopter_crash" => new() { Icons = new[] { "materials/editor/info_target.vmat" } },
            "info_target_server_only" => new() { Icons = new[] { "models/editor/info_target.vmdl" } },
            "info_target_vehicle_transition" => new() { Icons = new[] { "materials/editor/info_target.vmat" } },
            "info_teleport_destination" => new() { Icons = new[] { "models/editor/playerstart.vmdl" } },
            "info_teleport_magnet" => new() { Color = new Vector3(255, 0, 0) },
            "info_teleporter_countdown" => new() { Icons = new[] { "materials/editor/info_target.vmat" } },
            "info_visibility_box" => new() { Icons = new[] { "materials/editor/info_visibility_box.vmat" } },
            "info_world_layer" => new() { Icons = new[] { "materials/editor/info_world_layer.vmat" } },
            "infodecal" => new() { Icons = new[] { "models/editor/axis_helper_thick.vmdl" } },
            "item_ammo_357" => new() { Icons = new[] { "models/items/357ammo.vmdl" } },
            "item_ammo_357_large" => new() { Icons = new[] { "models/items/357ammobox.vmdl" } },
            "item_ammo_ar2" => new() { Icons = new[] { "models/items/combine_rifle_cartridge01.vmdl" } },
            "item_ammo_ar2_altfire" => new() { Icons = new[] { "models/items/combine_rifle_ammo01.vmdl" } },
            "item_ammo_ar2_large" => new() { Icons = new[] { "models/items/combine_rifle_cartridge01.vmdl" } },
            "item_ammo_crate" => new() { Icons = new[] { "models/items/ammocrate_rockets.vmdl" } },
            "item_ammo_crossbow" => new() { Icons = new[] { "models/items/crossbowrounds.vmdl" } },
            "item_ammo_pistol" => new() { Icons = new[] { "models/items/boxsrounds.vmdl" } },
            "item_ammo_pistol_large" => new() { Icons = new[] { "models/items/boxsrounds.vmdl" } },
            "item_ammo_smg1" => new() { Icons = new[] { "models/items/boxmrounds.vmdl" } },
            "item_ammo_smg1_grenade" => new() { Icons = new[] { "models/items/ar2_grenade.vmdl" } },
            "item_ammo_smg1_large" => new() { Icons = new[] { "models/items/boxmrounds.vmdl" } },
            "item_battery" => new() { Icons = new[] { "models/items/battery.vmdl" } },
            "item_box_buckshot" => new() { Icons = new[] { "models/items/boxbuckshot.vmdl" } },
            "item_combine_console" => new() { Icons = new[] { "models/props_combine/combine_consoles/vr_combine_interface_01.vmdl" } },
            "item_dynamic_resupply" => new() { Icons = new[] { "models/items/healthkit.vmdl" } },
            "item_healthcharger" => new() { Icons = new[] { "models/props_combine/combine_structures/health_charger_entity_mesh.vmdl" } },
            "item_healthcharger_DEPRECATED" => new() { Icons = new[] { "models/props_combine/health_charger001.vmdl" } },
            "item_healthkit" => new() { Icons = new[] { "models/items/healthkit.vmdl" } },
            "item_healthvial" => new() { Icons = new[] { "models/weapons/vr_alyxhealth/vr_health_pen.vmdl" } },
            "item_healthvial_DEPRECATED" => new() { Icons = new[] { "models/items/healthvial/healthvial.vmdl" } },
            "item_hlvr_clip_energygun" => new() { Icons = new[] { "models/weapons/vr_alyxgun/vr_alyxgun_clip.vmdl" } },
            "item_hlvr_clip_energygun_multiple" => new() { Icons = new[] { "models/weapons/vr_alyxgun/pistol_clip_holder.vmdl" } },
            "item_hlvr_clip_generic_pistol" => new() { Icons = new[] { "models/weapons/vr_alyxgun/vr_alyxgun_clip.vmdl" } },
            "item_hlvr_clip_generic_pistol_multiple" => new() { Icons = new[] { "models/weapons/vr_alyxgun/pistol_clip_holder.vmdl" } },
            "item_hlvr_clip_rapidfire" => new() { Icons = new[] { "models/weapons/vr_ipistol/capsule_power_cell.vmdl" } },
            "item_hlvr_clip_shotgun_multiple" => new() { Icons = new[] { "models/weapons/vr_ammo/shotgun_shell_ammo_box.vmdl" } },
            "item_hlvr_clip_shotgun_single" => new() { Icons = new[] { "models/weapons/vr_shotgun/shell_hand.vmdl" } },
            "item_hlvr_combine_console_tank" => new() { Icons = new[] { "models/props_combine/combine_consoles/glass_tank_01.vmdl" } },
            "item_hlvr_crafting_currency_large" => new() { Icons = new[] { "models/items/crafting_metal/crafting_resin_lrg5.vmdl" } },
            "item_hlvr_crafting_currency_small" => new() { Icons = new[] { "models/items/crafting_metal/resin_puck01.vmdl" } },
            "item_hlvr_grenade_bomb" => new() { Icons = new[] { "models/props/combine/combine_truck_gun_projectile.vmdl" } },
            "item_hlvr_grenade_frag" => new() { Icons = new[] { "models/weapons/vr_grenade/grenade_unarmed.vmdl" } },
            "item_hlvr_grenade_remote_sticky" => new() { Icons = new[] { "models/combine_helicopter/helicopter_bomb01.vmdl" } },
            "item_hlvr_grenade_xen" => new() { Icons = new[] { "models/weapons/vr_xen_grenade/vr_xen_grenade.vmdl" } },
            "item_hlvr_headcrab_gland" => new() { Icons = new[] { "models/props/headcrab_guts/headcrab_gland.vmdl" } },
            "item_hlvr_health_station_vial" => new() { Icons = new[] { "models/props_combine/health_charger/health_vial.vmdl" } },
            "item_hlvr_prop_ammobag" => new() { Icons = new[] { "models/items/combine_rifle_ammo01.vmdl" } },
            "item_hlvr_prop_battery" => new() { Icons = new[] { "models/props_combine/combine_battery/combine_battery.vmdl" } },
            "item_hlvr_weapon_energygun" => new() { Icons = new[] { "models/weapons/vr_alyxgun/vr_alyxgun.vmdl" } },
            "item_hlvr_weapon_generic_pistol" => new() { Icons = new[] { "models/weapons/vr_alyxgun/vr_alyxgun.vmdl" } },
            "item_hlvr_weapon_rapidfire" => new() { Icons = new[] { "models/weapons/vr_ipistol/vr_ipistol.vmdl" } },
            "item_hlvr_weapon_shotgun" => new() { Icons = new[] { "models/weapons/vr_shotgun/vr_shotgun_b.vmdl" } },
            "item_hlvr_weapon_tripmine" => new() { Icons = new[] { "models/weapons/vr_tripmine/tripmine.vmdl" } },
            "item_hlvr_weaponmodule_guidedmissle" => new() { Icons = new[] { "models/weapons/modules/module_missile.vmdl" } },
            "item_hlvr_weaponmodule_guidedmissle_cluster" => new() { Icons = new[] { "models/weapons/modules/module_missile_cluster.vmdl" } },
            "item_hlvr_weaponmodule_physcannon" => new() { Icons = new[] { "models/weapons/modules/module_ricochet.vmdl" } },
            "item_hlvr_weaponmodule_rapidfire" => new() { Icons = new[] { "models/weapons/modules/module_rapidfire.vmdl" } },
            "item_hlvr_weaponmodule_ricochet" => new() { Icons = new[] { "models/weapons/modules/module_ricochet.vmdl" } },
            "item_hlvr_weaponmodule_snark" => new() { Icons = new[] { "models/creatures/snark/snark.vmdl" } },
            "item_hlvr_weaponmodule_zapper" => new() { Icons = new[] { "models/weapons/vr_alyxgun/vr_alyxgun_attach_zap.vmdl" } },
            "item_item_crate" => new() { Icons = new[] { "models/props/supplycrate/supplycrate_01.vmdl" } },
            "item_rpg_round" => new() { Icons = new[] { "models/weapons/w_missile_closed.vmdl" } },
            "item_suit" => new() { Icons = new[] { "models/items/hevsuit.vmdl" } },
            "item_suitcharger" => new() { Icons = new[] { "models/props_combine/suit_charger001.vmdl" } },
            "keyframe_rope" => new() { Icons = new[] { "models/editor/axis_helper_thick.vmdl" } },
            "keyframe_track" => new() { Color = new Vector3(255, 200, 0) },
            "light_ambient" => new() { Icons = new[] { "materials/editor/light_ambient.vmat" } },
            "light_ambientocclusion" => new() { Icons = new[] { "materials/editor/light_ambientocclusion.vmat" } },
            "light_barn" => new() { Icons = new[] { "models/editor/spot.vmdl" } },
            "light_dynamic" => new() { Icons = new[] { "materials/editor/light.vmat" } },
            "light_environment" => new() { Icons = new[] { "models/editor/light_environment.vmdl", "materials/editor/light_environment_2.vmat", "models/editor/sun.vmdl" } },
            "light_importance_volume" => new() { Icons = new[] { "materials/editor/light_importance_volume.vmat" } },
            "light_irradvolume" => new() { Icons = new[] { "models/editor/iv_helper.vmdl" }, Color = new Vector3(225, 225, 80) },
            "light_omni" => new() { Icons = new[] { "materials/editor/light_omni.vmat", "models/editor/spot.vmdl" } },
            "light_omni2" => new() { Icons = new[] { "materials/editor/light_omni.vmat" } },
            "light_ortho" => new() { Icons = new[] { "models/editor/spot.vmdl" } },
            "light_rect" => new() { Icons = new[] { "models/editor/spot.vmdl" } },
            "light_sky" => new() { Icons = new[] { "materials/editor/light_sky.vmat" } },
            "light_spot" => new() { Icons = new[] { "materials/editor/light_spot_icon.vmat", "models/editor/spot.vmdl" } },
            "logic_achievement" => new() { Icons = new[] { "materials/editor/logic_achievement.vmat" } },
            "logic_auto" => new() { Icons = new[] { "materials/editor/logic_auto.vmat" } },
            "logic_autosave" => new() { Icons = new[] { "materials/editor/logic_autosave.vmat" } },
            "logic_branch" => new() { Icons = new[] { "materials/editor/logic_branch.vmat" } },
            "logic_case" => new() { Icons = new[] { "materials/editor/logic_case.vmat" } },
            "logic_choreographed_scene" => new() { Icons = new[] { "materials/editor/choreo_scene.vmat" }, Color = new Vector3(0, 0, 255) },
            "logic_collision_pair" => new() { Color = new Vector3(0, 255, 0) },
            "logic_compare" => new() { Icons = new[] { "materials/editor/logic_compare.vmat" } },
            "logic_distance_autosave" => new() { Icons = new[] { "materials/editor/logic_autosave.vmat" } },
            "logic_door_barricade" => new() { Icons = new[] { "materials/editor/logic_door_barricade.vmat" } },
            "logic_gameevent_listener" => new() { Icons = new[] { "materials/editor/game_event_listener.vmat" } },
            "logic_handsup_listener" => new() { Icons = new[] { "materials/editor/logic_hands_up.vmat" } },
            "logic_multicompare" => new() { Icons = new[] { "materials/editor/logic_multicompare.vmat" } },
            "logic_npc_counter_aabb" => new() { Icons = new[] { "materials/editor/math_counter.vmat" } },
            "logic_npc_counter_obb" => new() { Icons = new[] { "materials/editor/math_counter.vmat" } },
            "logic_npc_counter_radius" => new() { Icons = new[] { "materials/editor/math_counter.vmat" } },
            "logic_random_outputs" => new() { Icons = new[] { "materials/editor/logic_random_outputs.vmat" } },
            "logic_relay" => new() { Icons = new[] { "materials/editor/logic_relay.vmat" } },
            "logic_scene_list_manager" => new() { Icons = new[] { "materials/editor/choreo_manager.vmat" }, Color = new Vector3(0, 0, 255) },
            "logic_script" => new() { Icons = new[] { "materials/editor/logic_script.vmat" } },
            "logic_scripted_scenario" => new() { Icons = new[] { "materials/editor/choreo_scene.vmat" }, Color = new Vector3(0, 0, 255) },
            "logic_timer" => new() { Icons = new[] { "materials/editor/logic_timer.vmat" } },
            "map_preview_camera_path_node" => new() { Icons = new[] { "models/editor/camera.vmdl" } },
            "math_counter" => new() { Icons = new[] { "materials/editor/math_counter.vmat" } },
            "molotov_projectile" => new() { Icons = new[] { "models/weapons/w_eq_molotov.vmdl" } },
            "move_keyframed" => new() { Color = new Vector3(255, 170, 0) },
            "move_rope" => new() { Icons = new[] { "models/editor/axis_helper.vmdl" } },
            "move_track" => new() { Color = new Vector3(255, 0, 0) },
            "npc_antlion" => new() { Icons = new[] { "models/creatures/antlion/antlion.vmdl" } },
            "npc_antlion_grub" => new() { Icons = new[] { "models/antlion_grub.vmdl" } },
            "npc_antlion_template_maker" => new() { Icons = new[] { "materials/editor/npc_maker.vmat" }, Color = new Vector3(0, 0, 255) },
            "npc_antlionguard" => new() { Icons = new[] { "models/antlion_guard.vmdl" } },
            "npc_apcdriver" => new() { Icons = new[] { "models/roller.vmdl" } },
            "npc_barnacle" => new() { Icons = new[] { "models/creatures/barnacle/barnacle.vmdl" } },
            "npc_barney" => new() { Icons = new[] { "models/characters/barney/barney.vmdl" } },
            "npc_bullseye" => new() { Icons = new[] { "materials/editor/bullseye.vmat" }, Color = new Vector3(255, 0, 0) },
            "npc_clawscanner" => new() { Icons = new[] { "models/shield_scanner.vmdl" } },
            "npc_combine_advisor_roaming" => new() { Icons = new[] { "models/advisor.vmdl" } },
            "npc_combine_camera" => new() { Icons = new[] { "models/combine_camera/combine_camera.vmdl" } },
            "npc_combine_cannon" => new() { Icons = new[] { "models/combine_soldier.vmdl" } },
            "npc_combinedropship" => new() { Icons = new[] { "models/combine_dropship.vmdl" } },
            "npc_combinegunship" => new() { Icons = new[] { "models/creatures/gunship/gunship.vmdl" } },
            "npc_crabsynth" => new() { Icons = new[] { "models/Synth.vmdl" } },
            "npc_cranedriver" => new() { Icons = new[] { "models/roller.vmdl" } },
            "npc_crow" => new() { Icons = new[] { "models/creatures/crow/crow.vmdl" } },
            "npc_cscanner" => new() { Icons = new[] { "models/creatures/scanner/combine_scanner.vmdl" } },
            "npc_dog" => new() { Icons = new[] { "models/dog.vmdl" } },
            "npc_enemyfinder" => new() { Icons = new[] { "materials/editor/enemyfinder.vmat" }, Color = new Vector3(255, 150, 0) },
            "npc_enemyfinder_combinecannon" => new() { Color = new Vector3(255, 150, 0) },
            "npc_fastzombie" => new() { Icons = new[] { "models/Zombie/fast.vmdl" } },
            "npc_fastzombie_torso" => new() { Icons = new[] { "models/Zombie/Fast_torso.vmdl" } },
            "npc_fisherman" => new() { Icons = new[] { "models/Barney.vmdl" } },
            "npc_gman" => new() { Icons = new[] { "models/gman.vmdl" } },
            "npc_grenade_frag" => new() { Icons = new[] { "models/Weapons/w_grenade.vmdl" } },
            "npc_headcrab" => new() { Icons = new[] { "models/creatures/headcrab_classic/headcrab_classic.vmdl" } },
            "npc_headcrab_armored" => new() { Icons = new[] { "models/creatures/headcrab_armored/headcrab_armored.vmdl" } },
            "npc_headcrab_black" => new() { Icons = new[] { "models/creatures/headcrab_black/headcrab_black.vmdl" } },
            "npc_headcrab_fast" => new() { Icons = new[] { "models/creatures/headcrab/headcrab.vmdl" } },
            "npc_headcrab_runner" => new() { Icons = new[] { "models/creatures/headcrab_reviver/headcrab_reviver.vmdl" } },
            "npc_heli_avoidbox" => new() { Color = new Vector3(255, 255, 0) },
            "npc_heli_avoidsphere" => new() { Icons = new[] { "materials/editor/env_firesource.vmat" }, Color = new Vector3(255, 255, 0) },
            "npc_heli_nobomb" => new() { Color = new Vector3(255, 255, 0) },
            "npc_helicopter" => new() { Icons = new[] { "models/creatures/combine_helicopter/combine_helicopter.vmdl" } },
            "npc_hunter" => new() { Icons = new[] { "models/hunter.vmdl" } },
            "npc_hunter_maker" => new() { Icons = new[] { "materials/editor/npc_maker.vmat" } },
            "npc_ichthyosaur" => new() { Icons = new[] { "models/ichthyosaur.vmdl" } },
            "npc_launcher" => new() { Icons = new[] { "models/junk/w_traffcone.vmdl" } },
            "npc_maker" => new() { Icons = new[] { "materials/editor/npc_maker.vmat" } },
            "npc_manhack" => new() { Icons = new[] { "models/creatures/manhack/manhack.vmdl" } },
            "npc_metropolice" => new() { Icons = new[] { "models/characters/metrocop/metrocop.vmdl" } },
            "npc_missiledefense" => new() { Icons = new[] { "models/missile_defense.vmdl" } },
            "npc_monk" => new() { Icons = new[] { "models/Monk.vmdl" } },
            "npc_mortarsynth" => new() { Icons = new[] { "models/mortarsynth.vmdl" } },
            "npc_mossman" => new() { Icons = new[] { "models/mossman.vmdl" } },
            "npc_pigeon" => new() { Icons = new[] { "models/creatures/pigeon/pigeon.vmdl" } },
            "npc_poisonzombie" => new() { Icons = new[] { "models/Zombie/Poison.vmdl" } },
            "npc_rollermine" => new() { Icons = new[] { "models/roller.vmdl" } },
            "npc_seagull" => new() { Icons = new[] { "models/creatures/seagull/seagull.vmdl", "models/seagull.vmdl" } },
            "npc_sniper" => new() { Icons = new[] { "models/combine_soldier.vmdl" } },
            "npc_stalker" => new() { Icons = new[] { "models/Stalker.vmdl" } },
            "npc_strider" => new() { Icons = new[] { "models/creatures/strider/combine_strider.vmdl" } },
            "npc_template_maker" => new() { Icons = new[] { "materials/editor/npc_maker.vmat" } },
            "npc_turret_citizen" => new() { Icons = new[] { "models/props/citizen_battery_turret.vmdl" } },
            "npc_turret_floor" => new() { Icons = new[] { "models/combine_turrets/floor_turret.vmdl" } },
            "npc_turret_ground" => new() { Icons = new[] { "models/combine_turrets/ground_turret.vmdl" } },
            "npc_vehicledriver" => new() { Icons = new[] { "models/roller.vmdl" } },
            "npc_vr_citizen_female" => new() { Icons = new[] { "models/characters/citizens/citizens_female.vmdl" } },
            "npc_vr_citizen_male" => new() { Icons = new[] { "models/characters/citizens/citizens_male.vmdl" } },
            "npc_zombie" => new() { Icons = new[] { "models/creatures/zombie_classic/zombie_classic.vmdl" } },
            "npc_zombie_blind" => new() { Icons = new[] { "models/creatures/zombie_blind/zombie_blind.vmdl" } },
            "npc_zombie_torso" => new() { Icons = new[] { "models/creatures/zombie_classic/zombie_classic_torso.vmdl" } },
            "npc_zombine" => new() { Icons = new[] { "models/Zombie/zombie_soldier.vmdl" } },
            "path_corner" => new() { Color = new Vector3(247, 181, 82) },
            "path_corner_crash" => new() { Color = new Vector3(255, 0, 0) },
            "path_track" => new() { Color = new Vector3(255, 192, 0) },
            "phys_ballsocket" => new() { Icons = new[] { "materials/editor/phys_ballsocket.vmat", "models/editor/axis_helper.vmdl" } },
            "phys_constraint" => new() { Icons = new[] { "models/editor/axis_helper_thick.vmdl" } },
            "phys_convert" => new() { Color = new Vector3(0, 0, 255) },
            "phys_genericconstraint" => new() { Icons = new[] { "models/editor/axis_helper.vmdl" } },
            "phys_hinge" => new() { Icons = new[] { "models/editor/axis_helper.vmdl" } },
            "phys_hinge_local" => new() { Icons = new[] { "models/editor/axis_helper.vmdl" } },
            "phys_lengthconstraint" => new() { Icons = new[] { "models/editor/axis_helper.vmdl" } },
            "phys_pulleyconstraint" => new() { Icons = new[] { "models/editor/axis_helper.vmdl" } },
            "phys_ragdollconstraint" => new() { Icons = new[] { "models/editor/axis_helper.vmdl" } },
            "phys_ragdollmagnet" => new() { Icons = new[] { "materials/editor/info_target.vmat" } },
            "phys_slideconstraint" => new() { Icons = new[] { "models/editor/axis_helper.vmdl" } },
            "phys_splineconstraint" => new() { Icons = new[] { "models/editor/axis_helper_thick.vmdl" } },
            "phys_spring" => new() { Icons = new[] { "models/editor/axis_helper.vmdl" } },
            "phys_wheelconstraint" => new() { Icons = new[] { "models/editor/axis_helper.vmdl" } },
            "point_aimat" => new() { Icons = new[] { "models/editor/point_aimat.vmdl" } },
            "point_antlion_repellant" => new() { Color = new Vector3(0, 0, 255) },
            "point_bugbait" => new() { Color = new Vector3(255, 255, 0) },
            "point_camera" => new() { Icons = new[] { "models/editor/camera.vmdl" } },
            "point_camera_vertical_fov" => new() { Icons = new[] { "models/editor/camera.vmdl" } },
            "point_clientui_world_movie_panel" => new() { Color = new Vector3(20, 140, 20) },
            "point_clientui_world_text_panel" => new() { Color = new Vector3(20, 140, 20) },
            "point_devshot_camera" => new() { Icons = new[] { "models/editor/camera.vmdl" } },
            "point_dz_dronegun" => new() { Icons = new[] { "models/props_survival/dronegun.vmdl" } },
            "point_gamestats_counter" => new() { Color = new Vector3(0, 255, 0) },
            "point_grabbable" => new() { Icons = new[] { "materials/editor/point_grabbable.vmat" } },
            "point_hlvr_player_input_modifier" => new() { Icons = new[] { "materials/editor/point_hlvr_player_input_modifier.vmat" } },
            "point_hlvr_strip_player" => new() { Icons = new[] { "materials/editor/point_hlvr_strip_player.vmat" } },
            "point_instructor_event" => new() { Icons = new[] { "materials/editor/env_instructor_hint.vmat" } },
            "point_nav_walkable" => new() { Icons = new[] { "materials/editor/nav_walkable.vmat" } },
            "point_soundevent" => new() { Icons = new[] { "materials/editor/ambient_generic.vmat", "materials/editor/snd_event.vmat" } },
            "point_spotlight" => new() { Icons = new[] { "models/editor/cone_helper.vmdl" } },
            "point_teleport" => new() { Icons = new[] { "models/editor/axis_helper_thick.vmdl" } },
            "point_template" => new() { Icons = new[] { "materials/editor/point_template.vmat" } },
            "point_value_remapper" => new() { Icons = new[] { "models/editor/axis_helper_thick.vmdl" } },
            "point_viewcontrol" => new() { Icons = new[] { "models/editor/camera.vmdl" } },
            "point_workplane" => new() { Icons = new[] { "models/editor/axis_helper_thick.vmdl" } },
            "point_worldtext" => new() { Icons = new[] { "models/editor/axis_helper_thick.vmdl" }, Color = new Vector3(20, 140, 20) },
            "postprocess_controller" => new() { Icons = new[] { "materials/editor/postprocess_controller.vmat" }, Color = new Vector3(255, 255, 255) },
            "prop_coreball" => new() { Icons = new[] { "models/props_combine/coreball.vmdl" } },
            "prop_counter" => new() { Icons = new[] { "models/props_survival/safe/safe.vmdl" } },
            "prop_exploding_barrel" => new() { Icons = new[] { "models/props/coop_cementplant/exloding_barrel/exploding_barrel.vmdl" } },
            "prop_handpose" => new() { Icons = new[] { "models/editormodel.vmdl" } },
            "prop_hlvr_crafting_station" => new() { Icons = new[] { "models/props_combine/combine_printer/combine_crafting_station.vmdl" } },
            "prop_reviver_heart" => new() { Icons = new[] { "models/creatures/headcrab_reviver/reviver_heart.vmdl" } },
            "prop_static" => new() { Icons = new[] { "models/static.vmdl" }, Color = new Vector3(255, 255, 0) },
            "save_photogrammetry_anchor" => new() { Icons = new[] { "materials/editor/save_photogrammetry_anchor.vmat" } },
            "scripted_sentence" => new() { Icons = new[] { "materials/editor/scripted_sentence.vmat" } },
            "scripted_sequence" => new() { Icons = new[] { "models/editor/scripted_sequence.vmdl" } },
            "scripted_target" => new() { Icons = new[] { "materials/editor/info_target.vmat" } },
            "shadow_control" => new() { Icons = new[] { "materials/editor/shadow_control.vmat" } },
            "sky_camera" => new() { Color = new Vector3(0, 0, 255) },
            "smokegrenade_projectile" => new() { Icons = new[] { "models/weapons/w_eq_smokegrenade.vmdl" } },
            "snd_event_alignedbox" => new() { Icons = new[] { "materials/editor/snd_event.vmat" } },
            "snd_event_param" => new() { Icons = new[] { "materials/editor/snd_opvar_set.vmat" } },
            "snd_event_path_corner" => new() { Icons = new[] { "materials/editor/snd_event.vmat" } },
            "snd_event_point" => new() { Icons = new[] { "materials/editor/snd_event.vmat" } },
            "snd_opvar_set" => new() { Icons = new[] { "materials/editor/snd_opvar_set.vmat" } },
            "snd_opvar_set_aabb" => new() { Icons = new[] { "materials/editor/snd_opvar_set.vmat" } },
            "snd_opvar_set_obb" => new() { Icons = new[] { "materials/editor/snd_opvar_set.vmat" } },
            "snd_opvar_set_path_corner" => new() { Icons = new[] { "materials/editor/snd_opvar_set.vmat" } },
            "snd_opvar_set_point" => new() { Icons = new[] { "materials/editor/snd_opvar_set.vmat" } },
            "snd_opvar_set_wind_obb" => new() { Icons = new[] { "materials/editor/snd_opvar_set.vmat" } },
            "snd_sound_area_obb" => new() { Icons = new[] { "materials/editor/snd_opvar_set.vmat" } },
            "snd_sound_area_sphere" => new() { Icons = new[] { "materials/editor/snd_opvar_set.vmat" } },
            "snd_soundscape" => new() { Icons = new[] { "materials/editor/env_soundscape.vmat" } },
            "snd_soundscape_proxy" => new() { Icons = new[] { "materials/editor/env_soundscape.vmat" } },
            "snd_soundscape_triggerable" => new() { Icons = new[] { "materials/editor/env_soundscape.vmat" } },
            "snd_stack_save" => new() { Icons = new[] { "materials/editor/snd_event.vmat" } },
            "sound_opvar_set" => new() { Icons = new[] { "materials/editor/ambient_generic.vmat" } },
            "tanktrain_ai" => new() { Icons = new[] { "materials/editor/tanktrain_ai.vmat" } },
            "tanktrain_aitarget" => new() { Icons = new[] { "materials/editor/tanktrain_aitarget.vmat" } },
            "team_select" => new() { Icons = new[] { "models/editor/team_select.vmdl" } },
            "terrorist_team_intro" => new() { Icons = new[] { "models/editor/terrorist_team_intro.vmdl" } },
            "test_traceline" => new() { Color = new Vector3(255, 255, 255) },
            "tutorial_npc_blocker" => new() { Icons = new[] { "materials/editor/info_target.vmat" } },
            "vgui_movie_display" => new() { Icons = new[] { "models/editor/axis_helper_thick.vmdl" } },
            "vgui_slideshow_display" => new() { Icons = new[] { "models/editor/axis_helper_thick.vmdl" } },
            "visibility_hint" => new() { Icons = new[] { "materials/editor/visibility_hint.vmat" } },
            "vr_teleport_marker" => new() { Icons = new[] { "models/effects/teleport/teleport_marker.vmdl" } },
            "water_lod_control" => new() { Icons = new[] { "materials/editor/waterlodcontrol.vmat" } },
            "weapon_357" => new() { Icons = new[] { "models/weapons/w_357.vmdl" } },
            "weapon_alyxgun" => new() { Icons = new[] { "models/weapons/W_Alyx_Gun.vmdl" } },
            "weapon_annabelle" => new() { Icons = new[] { "models/weapons/W_annabelle.vmdl" } },
            "weapon_ar2" => new() { Icons = new[] { "models/weapons/vr_irifle/vr_irifle.vmdl" } },
            "weapon_bugbait" => new() { Icons = new[] { "models/spore.vmdl" } },
            "weapon_crossbow" => new() { Icons = new[] { "models/weapons/w_crossbow.vmdl" } },
            "weapon_crowbar" => new() { Icons = new[] { "models/weapons/w_crowbar.vmdl" } },
            "weapon_frag" => new() { Icons = new[] { "models/weapons/w_grenade.vmdl" } },
            "weapon_physcannon" => new() { Icons = new[] { "models/weapons/w_physics.vmdl" } },
            "weapon_pistol" => new() { Icons = new[] { "models/weapons/vr_pistol/vr_pistol.vmdl" } },
            "weapon_rpg" => new() { Icons = new[] { "models/weapons/w_rocket_launcher.vmdl" } },
            "weapon_shotgun" => new() { Icons = new[] { "models/weapons/vr_shotgun/vr_shotgun.vmdl" } },
            "weapon_smg1" => new() { Icons = new[] { "models/weaponsmodels/weapons/vr_smg/vr_smg.vmdl" } },
            "weapon_striderbuster" => new() { Icons = new[] { "models/magnusson_device.vmdl" } },
            "weapon_stunstick" => new() { Icons = new[] { "models/weapons/vr_baton/vr_baton.vmdl" } },
            "weapon_zipline" => new() { Icons = new[] { "models/weapons/w_crossbow.vmdl" } },
            "xen_flora_animatedmover" => new() { Icons = new[] { "models/props/xen_infestation_v2/xen_v2_floater_jellybobber.vmdl" } },
            "xen_foliage_bloater" => new() { Icons = new[] { "models/props/xen_infestation/boomerplant_01.vmdl" } },
            "xen_foliage_grenade_spawner" => new() { Icons = new[] { "models/props/xen_infestation/xen_grenade_plant.vmdl" } },
            "xen_foliage_turret" => new() { Icons = new[] { "models/props/xen_infestation/xen_grenade_plant.vmdl" } },
            "xen_hearing_flower" => new() { Icons = new[] { "models/props/xen/xen_coralear04.vmdl" } },
            _ => null,
        };
    }
}
