using System.Diagnostics;
using System.Globalization;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.Json;

// Generates C# definition classes from the SchemaExplorer schema dump. What gets generated, and where it
// goes, is described by a SchemaTarget (see SchemaConverter.AnimLib.cs).
//
// The classes only declare their properties, with the schema defaults as initializers. They are marked
// [KV3Transfer], and the KV3Transfer source generator writes the constructor reading them from KeyValues3.
// Keys follow that generator's naming rule, and [KVProperty] names the ones that do not.
//
// Generated files are hand edited afterwards, so a regen never overwrites them. Instead the schema the
// files were last generated from (pinned in the target's generated-from file) is generated again as a
// merge base, and each file gets a three-way merge of (current file, previous generation, new generation).
// Files deleted by hand stay deleted, and new schema classes are created.
//
// Usage: dotnet run [-- [--target <name>] [--offline] [--dry-run] [--baseline-dir <dir>]]
//   --target            which target to generate, defaults to the only one
//   --offline           do not fetch, use the last saved schema
//   --dry-run           report what would change without writing
//   --baseline-dir      use an already generated folder as the merge base instead of the pinned schema
//
// The merge base is generated by the current converter, so changes to the converter output itself are
// not merged on their own. For those, dry run the previous converter version and pass its output folder
// (printed temp path) as --baseline-dir.

const string SchemaRepository = "ValveResourceFormat/SchemaExplorer";
const string SchemaPath = "schemas/cs2.json";

SchemaTarget[] targets = [new AnimLibTarget()];

var offline = args.Contains("--offline");
var dryRun = args.Contains("--dry-run");
var baselineDirArg = OptionValue("--baseline-dir");
var targetName = OptionValue("--target");

var target = targetName == null
    ? targets.Single()
    : targets.FirstOrDefault(t => t.Name == targetName) ?? throw new ArgumentException($"Unknown target {targetName}, expected one of: {string.Join(", ", targets.Select(t => t.Name))}");

var toolDir = Path.GetDirectoryName(CurrentFileName()) ?? throw new InvalidOperationException();
var repositoryDir = WalkUpDir(CurrentFileName(), 3);
var cacheDir = Path.Combine(toolDir, "cache");
var generatedFromFile = Path.Combine(toolDir, target.GeneratedFromFileName);
var destinationDir = Path.Combine(repositoryDir, target.DestinationDir);

Converter.Test(target);

var (latestSha, latestSchemaFile) = await GetLatestSchema();
Console.WriteLine($"Using schema {SchemaRepository}@{latestSha}");

var newDir = Path.Combine(Path.GetTempPath(), "SchemaConverter", target.Name, "new");
Generate(Schema.Load(latestSchemaFile, target), newDir);

string? baselineDir = null;
string? baselineSha = null;

if (baselineDirArg != null)
{
    baselineDir = Path.GetFullPath(baselineDirArg);
}
else if (File.Exists(generatedFromFile))
{
    baselineSha = File.ReadAllText(generatedFromFile).Trim();
    var baselineSchemaFile = await GetSchemaAtCommit(baselineSha);

    if (baselineSchemaFile != null)
    {
        baselineDir = Path.Combine(Path.GetTempPath(), "SchemaConverter", target.Name, "baseline");
        Generate(Schema.Load(baselineSchemaFile, target), baselineDir);
    }
    else
    {
        Console.WriteLine($"Previous schema {baselineSha} is not available, existing files will be left alone.");
    }
}
else
{
    Console.WriteLine($"No {Path.GetFileName(generatedFromFile)}, existing files will be left alone.");
}

var hasConflicts = MergeInto(destinationDir, baselineDir, newDir);

if (!dryRun)
{
    File.WriteAllText(generatedFromFile, latestSha + "\n");
    Process.Start("dotnet", $"build \"{Path.Combine(repositoryDir, target.BuildProject)}\" /p:NoWarn=CA1812")?.WaitForExit();
}

return hasConflicts ? 1 : 0;

string? OptionValue(string option)
{
    var index = Array.IndexOf(args, option);
    return index >= 0 && index + 1 < args.Length ? args[index + 1] : null;
}

async Task<(string Sha, string File)> GetLatestSchema()
{
    var latestShaFile = Path.Combine(cacheDir, "latest.txt");

    if (!offline)
    {
        try
        {
            using var http = CreateHttpClient();
            var commitsUrl = $"https://api.github.com/repos/{SchemaRepository}/commits?path={SchemaPath}&per_page=1";
            using var commits = JsonDocument.Parse(await http.GetStringAsync(commitsUrl));
            var sha = commits.RootElement[0].GetProperty("sha").GetString() ?? throw new InvalidDataException("Commit without sha");

            var file = await GetSchemaAtCommit(sha) ?? throw new InvalidDataException($"Failed to download schema at {sha}");
            File.WriteAllText(latestShaFile, sha);
            return (sha, file);
        }
        catch (Exception e) when (e is HttpRequestException or TaskCanceledException)
        {
            Console.WriteLine($"Failed to fetch the latest schema ({e.Message}), falling back to the saved one.");
        }
    }

    if (!File.Exists(latestShaFile))
    {
        throw new InvalidOperationException("No saved schema to fall back to, run once with network access.");
    }

    var savedSha = File.ReadAllText(latestShaFile).Trim();
    return (savedSha, CachedSchemaFile(savedSha));
}

async Task<string?> GetSchemaAtCommit(string sha)
{
    var file = CachedSchemaFile(sha);
    if (File.Exists(file))
    {
        return file;
    }

    if (offline)
    {
        return null;
    }

    try
    {
        using var http = CreateHttpClient();
        var content = await http.GetByteArrayAsync($"https://raw.githubusercontent.com/{SchemaRepository}/{sha}/{SchemaPath}");

        Directory.CreateDirectory(cacheDir);
        File.WriteAllBytes(file, content);
        return file;
    }
    catch (Exception e) when (e is HttpRequestException or TaskCanceledException)
    {
        Console.WriteLine($"Failed to fetch schema at {sha} ({e.Message}).");
        return null;
    }
}

string CachedSchemaFile(string sha) => Path.Combine(cacheDir, $"cs2-{sha}.json");

static HttpClient CreateHttpClient()
{
    var http = new HttpClient { Timeout = TimeSpan.FromSeconds(30) };
    http.DefaultRequestHeaders.UserAgent.ParseAdd("VRF-SchemaConverter");
    return http;
}

bool MergeInto(string targetDir, string? baseDir, string generatedDir)
{
    var created = 0;
    var updated = 0;
    var merged = 0;
    List<string> conflicts = [];
    List<string> notes = [];

    var generatedFiles = Directory.GetFiles(generatedDir, "*.cs", SearchOption.AllDirectories)
        .Select(f => Path.GetRelativePath(generatedDir, f))
        .Order(StringComparer.Ordinal);

    foreach (var relativePath in generatedFiles)
    {
        var newText = ReadNormalized(Path.Combine(generatedDir, relativePath));
        var basePath = baseDir != null ? Path.Combine(baseDir, relativePath) : null;
        var baseText = basePath != null && File.Exists(basePath) ? ReadNormalized(basePath) : null;
        var targetPath = Path.Combine(targetDir, relativePath);

        if (!File.Exists(targetPath))
        {
            if (baseText != null)
            {
                // Generated before and deleted by hand since
                if (baseText != newText)
                {
                    notes.Add($"deleted locally, schema changed: {relativePath}");
                }

                continue;
            }

            if (!dryRun)
            {
                Directory.CreateDirectory(Path.GetDirectoryName(targetPath)!);
                WriteNormalized(targetPath, newText);
            }

            Console.WriteLine($"Created {relativePath}");
            created++;
            continue;
        }

        if (baseText == null)
        {
            if (ReadNormalized(targetPath) != newText)
            {
                notes.Add($"not generated before, kept as is: {relativePath}");
            }

            continue;
        }

        if (baseText == newText)
        {
            continue;
        }

        var currentText = ReadNormalized(targetPath);

        if (currentText == baseText)
        {
            if (!dryRun)
            {
                WriteNormalized(targetPath, newText);
            }

            Console.WriteLine($"Updated {relativePath}");
            updated++;
            continue;
        }

        var (mergedText, conflicted) = MergeText(currentText, baseText, newText);

        if (!dryRun)
        {
            WriteNormalized(targetPath, mergedText);
        }

        if (conflicted)
        {
            conflicts.Add(relativePath);
        }
        else
        {
            Console.WriteLine($"Merged {relativePath}");
            merged++;
        }
    }

    // Classes that left the schema
    if (baseDir != null)
    {
        foreach (var basePath in Directory.GetFiles(baseDir, "*.cs", SearchOption.AllDirectories))
        {
            var relativePath = Path.GetRelativePath(baseDir, basePath);
            var targetPath = Path.Combine(targetDir, relativePath);

            if (File.Exists(Path.Combine(generatedDir, relativePath)) || !File.Exists(targetPath))
            {
                continue;
            }

            notes.Add($"no longer in the schema: {relativePath}");
        }
    }

    Console.WriteLine();
    Console.WriteLine($"{created} created, {updated} updated, {merged} merged, {conflicts.Count} conflicted{(dryRun ? " (dry run)" : "")}");

    foreach (var note in notes)
    {
        Console.WriteLine($"  {note}");
    }

    foreach (var conflict in conflicts)
    {
        Console.WriteLine($"  CONFLICT: {conflict}");
    }

    return conflicts.Count > 0;
}

static (string Text, bool Conflicted) MergeText(string current, string baseline, string generated)
{
    var tempDir = Directory.CreateTempSubdirectory("SchemaConverterMerge").FullName;

    try
    {
        var currentFile = Path.Combine(tempDir, "current");
        var baseFile = Path.Combine(tempDir, "base");
        var newFile = Path.Combine(tempDir, "new");
        File.WriteAllText(currentFile, current);
        File.WriteAllText(baseFile, baseline);
        File.WriteAllText(newFile, generated);

        var startInfo = new ProcessStartInfo("git")
        {
            RedirectStandardOutput = true,
            UseShellExecute = false,
        };

        foreach (var argument in (string[])["merge-file", "-p", "-L", "manual", "-L", "previous schema", "-L", "new schema", currentFile, baseFile, newFile])
        {
            startInfo.ArgumentList.Add(argument);
        }

        using var process = Process.Start(startInfo) ?? throw new InvalidOperationException("Failed to start git");
        var output = process.StandardOutput.ReadToEnd();
        process.WaitForExit();

        // git merge-file exits with the number of conflicts, negative on errors
        if (process.ExitCode < 0)
        {
            throw new InvalidOperationException($"git merge-file failed with {process.ExitCode}");
        }

        return (output, process.ExitCode > 0);
    }
    finally
    {
        Directory.Delete(tempDir, recursive: true);
    }
}

static string ReadNormalized(string path) => File.ReadAllText(path).ReplaceLineEndings("\n");

static void WriteNormalized(string path, string text) => File.WriteAllText(path, text, new UTF8Encoding(false));

void Generate(Schema schema, string outputDir)
{
    if (Directory.Exists(outputDir))
    {
        Directory.Delete(outputDir, recursive: true);
    }

    Directory.CreateDirectory(outputDir);

    var converter = new Converter(schema, target);

    foreach (var type in schema.Types)
    {
        var internalName = converter.ConvertClassName(type.Name, target.SourceNameSpace);
        var destinationDirLocal = target.ChooseFolder(converter, internalName, outputDir);
        Directory.CreateDirectory(destinationDirLocal);

        var writer = new StringBuilder();

        if (type is not SchemaEnum)
        {
            writer.Append("using ValveResourceFormat.Serialization.KeyValues;\n"); // global using?
        }

        writer.Append(CultureInfo.InvariantCulture, $"namespace {target.DestinationNameSpace};\n");
        writer.Append('\n');

        // Nested types go inside partial declarations of the types they belong to
        var outers = converter.OuterTypes(internalName);
        for (var i = 0; i < outers.Count; i++)
        {
            var indent = new string(' ', i * 4);
            writer.Append(CultureInfo.InvariantCulture, $"{indent}{target.ClassKeywords(converter, outers[i])} {converter.SimpleName(outers[i])}\n");
            writer.Append(CultureInfo.InvariantCulture, $"{indent}{{\n");
        }

        var typeWriter = new StringBuilder();
        converter.Write(type, typeWriter);

        foreach (var line in typeWriter.ToString().TrimEnd('\n').Split('\n'))
        {
            writer.Append(line.Length > 0 ? new string(' ', outers.Count * 4) + line : line).Append('\n');
        }

        for (var i = outers.Count - 1; i >= 0; i--)
        {
            writer.Append(CultureInfo.InvariantCulture, $"{new string(' ', i * 4)}}}\n");
        }

        WriteNormalized(Path.Combine(destinationDirLocal, converter.TypeReference(internalName) + ".cs"), writer.ToString());
    }
}

string CurrentFileName([CallerFilePath] string csFilePath = "")
{
    return csFilePath ?? throw new InvalidOperationException();
}

static string WalkUpDir(string path, int levels)
{
    var currentPath = path;
    for (var i = 0; i < levels; i++)
    {
        currentPath = Path.GetDirectoryName(currentPath) ?? throw new InvalidOperationException("Cannot walk up any further.");
    }

    return currentPath;
}

/// <summary>
/// What to generate from the schema and where to put it.
/// </summary>
abstract class SchemaTarget
{
    /// <summary>Selects the target with --target.</summary>
    public abstract string Name { get; }

    /// <summary>Output folder, relative to the repository root.</summary>
    public abstract string DestinationDir { get; }

    /// <summary>Namespace of the generated files.</summary>
    public abstract string DestinationNameSpace { get; }

    /// <summary>Project built after a regen, relative to the repository root.</summary>
    public abstract string BuildProject { get; }

    /// <summary>Pins the schema the files were last generated from, next to the converter.</summary>
    public virtual string GeneratedFromFileName => $"generated-from-{Name}.txt";

    /// <summary>Prefix stripped from schema class names, e.g. "Nm" for CNmClipNode.</summary>
    public abstract string SourceNameSpace { get; }

    /// <summary>Whether a schema class or enum is generated.</summary>
    public abstract bool IsIncluded(string module, string name);

    /// <summary>Schema types mapped to existing C# types, on top of the common ones.</summary>
    public virtual IReadOnlyDictionary<string, string> TypeMap { get; } = new Dictionary<string, string>();

    /// <summary>Folder a generated type goes in, under the output folder.</summary>
    public virtual string ChooseFolder(Converter converter, string fileName, string outputDir) => outputDir;

    /// <summary>The C# declaration keywords for a generated class, e.g. "partial class".</summary>
    public virtual string ClassKeywords(Converter converter, string className) => "partial class";

    /// <summary>Adjusts a converted class name, e.g. to drop a suffix.</summary>
    public virtual string PostProcessClassName(string className) => className;

    /// <summary>Checks the target specific conversions.</summary>
    public virtual void Test(Converter converter)
    {
    }
}

abstract record SchemaType(string Name);

/// <param name="Defaults">The schema default of each field by name, from MGetKV3ClassDefaults.</param>
record SchemaClass(string Name, string? Parent, List<SchemaField> Fields, Dictionary<string, JsonElement> Defaults) : SchemaType(Name);

record SchemaEnum(string Name, string BaseType, List<(string Name, long Value)> Members) : SchemaType(Name);

/// <param name="Type">The outer type name, e.g. CUtlVector.</param>
/// <param name="Args">The template arguments as declared in C++, e.g. "int16, 5".</param>
record SchemaField(string Type, string? Args, string Name);

class Schema
{
    public required List<SchemaType> Types { get; init; }

    public static Schema Load(string path, SchemaTarget target)
    {
        using var stream = File.OpenRead(path);
        using var document = JsonDocument.Parse(stream);
        var root = document.RootElement;

        List<SchemaType> types = [];

        foreach (var @class in root.GetProperty("classes").EnumerateArray())
        {
            var name = @class.GetProperty("name").GetString()!;
            if (!target.IsIncluded(@class.GetProperty("module").GetString()!, name))
            {
                continue;
            }

            string? parent = null;
            if (@class.TryGetProperty("parents", out var parents) && parents.GetArrayLength() > 0)
            {
                parent = parents[0].GetProperty("name").GetString();
            }

            List<SchemaField> fields = [];
            if (@class.TryGetProperty("fields", out var fieldsElement))
            {
                foreach (var field in fieldsElement.EnumerateArray())
                {
                    var type = field.GetProperty("type");

                    // Raw pointers are runtime state, not serialized data
                    if (DeclaredTypeName(type).Contains('*', StringComparison.Ordinal))
                    {
                        continue;
                    }

                    string? args = null;

                    if (type.TryGetProperty("inner", out var inner) && type.GetProperty("category").GetString() == "atomic")
                    {
                        args = DeclaredTypeName(inner);
                        if (type.TryGetProperty("count", out var count))
                        {
                            args += $", {count.GetInt32()}";
                        }
                    }

                    var outerName = type.GetProperty("category").GetString() == "atomic" ? type.GetProperty("name").GetString()! : DeclaredTypeName(type);
                    fields.Add(new SchemaField(outerName, args, field.GetProperty("name").GetString()!));
                }
            }

            Dictionary<string, JsonElement> defaults = [];
            if (@class.TryGetProperty("metadata", out var metadata))
            {
                foreach (var entry in metadata.EnumerateArray())
                {
                    if (entry.GetProperty("name").GetString() == "MGetKV3ClassDefaults"
                        && entry.TryGetProperty("value", out var value) && value.ValueKind == JsonValueKind.Object)
                    {
                        foreach (var property in value.EnumerateObject())
                        {
                            defaults[property.Name] = property.Value.Clone();
                        }
                    }
                }
            }

            types.Add(new SchemaClass(name, parent, fields, defaults));
        }

        foreach (var @enum in root.GetProperty("enums").EnumerateArray())
        {
            var name = @enum.GetProperty("name").GetString()!;
            if (!target.IsIncluded(@enum.GetProperty("module").GetString()!, name))
            {
                continue;
            }

            var members = @enum.GetProperty("members").EnumerateArray()
                .Select(m => (m.GetProperty("name").GetString()!, m.GetProperty("value").GetInt64()))
                .ToList();

            types.Add(new SchemaEnum(name, @enum.GetProperty("alignment").GetString()!, members));
        }

        return new Schema { Types = types };
    }

    // The type as it would be declared in C++, e.g. "CUtlVector< CGlobalSymbol >" or "CNmClip*"
    private static string DeclaredTypeName(JsonElement type)
    {
        var category = type.GetProperty("category").GetString();

        if (category == "ptr")
        {
            return DeclaredTypeName(type.GetProperty("inner")) + "*";
        }

        var name = type.GetProperty("name").GetString()!;

        if (category == "atomic" && type.TryGetProperty("inner", out var inner))
        {
            var args = DeclaredTypeName(inner);
            if (type.TryGetProperty("count", out var count))
            {
                args += $", {count.GetInt32()}";
            }

            return $"{name}< {args} >";
        }

        return name;
    }
}

class Converter
{
    private readonly SchemaTarget target;
    private readonly HashSet<string> enumTypes = [];
    private readonly Dictionary<string, Dictionary<string, long>> enumMembers = [];
    private readonly Dictionary<string, string?> classHierarchies = [];
    private readonly Dictionary<string, HashSet<string>> ownPropertyNames = [];

    // Properties of each class and of the classes deriving from it, which a nested type must not share a name with
    private readonly Dictionary<string, HashSet<string>> propertyNames = [];

    private static readonly HashSet<string> MatchingTypes =
    [
        "bool", "float", "double",
    ];

    private static readonly Dictionary<string, string> CommonTypeMap = new()
    {
        { "uint8_t", "byte" },
        { "uint8", "byte" },
        { "int8_t", "sbyte" },
        { "uint16_t", "ushort" },
        { "uint16", "ushort" },
        { "int16_t", "short" },
        { "int16", "short" },
        { "uint32_t", "uint" },
        { "int32_t", "int" },
        { "int32", "int" },
        { "uint32", "uint" },
        { "float32", "float" },
        { "uint64_t", "ulong" },
        { "int64_t", "long" },
        { "uint64", "ulong" },
        { "int64", "long" },

        { "CUtlString", "string" },
        { "CUtlBinaryBlock", "byte[]" },
        { "Vector2D", "Vector2" },
        { "Vector", "Vector3" },
        { "CResourceName", "string" },
        { "KeyValues3", "KVObject" },
    };

    public Converter(Schema schema, SchemaTarget target)
    {
        this.target = target;

        foreach (var type in schema.Types)
        {
            switch (type)
            {
                case SchemaClass @class:
                    classHierarchies[ConvertClassName(@class.Name, target.SourceNameSpace)] = @class.Parent is not null ? ConvertClassName(@class.Parent, target.SourceNameSpace) : null;
                    ownPropertyNames[ConvertClassName(@class.Name, target.SourceNameSpace)] = [.. @class.Fields.Select(f => ConvertHungarianNotation(f.Name))];
                    break;
                case SchemaEnum @enum:
                    enumTypes.Add(ConvertClassName(@enum.Name, target.SourceNameSpace));
                    enumMembers[ConvertClassName(@enum.Name, target.SourceNameSpace)] = @enum.Members.ToDictionary(m => m.Name, m => m.Value);
                    break;
            }
        }

        CollectPropertyNames();
    }

    private string SourceNameSpace => target.SourceNameSpace;

    private void CollectPropertyNames()
    {
        foreach (var (@class, properties) in ownPropertyNames)
        {
            for (string? ancestor = @class; ancestor != null; ancestor = classHierarchies.GetValueOrDefault(ancestor))
            {
                if (!propertyNames.TryGetValue(ancestor, out var names))
                {
                    propertyNames[ancestor] = names = [];
                }

                names.UnionWith(properties);
            }
        }
    }

    public bool IsEnum(string type) => enumTypes.Contains(type);

    /*
        StateNode__TimedEvent__Comparison -> StateNode.TimedEvent.Comparison. A nested type named like a property of
        the type it is in gets a Type suffix (FloatMathNode__Operator -> FloatMathNode.OperatorType), or the outer
        name as a prefix when it already ends in Type (ClothEvent__Type -> ClothEvent.ClothEventType)
    */
    public string TypeReference(string internalName)
    {
        if (internalName.EndsWith("[]", StringComparison.Ordinal))
        {
            return TypeReference(internalName[..^2]) + "[]";
        }

        var parts = internalName.Split("__");
        if (parts.Length == 1)
        {
            return internalName;
        }

        var reference = new StringBuilder(parts[0]);
        var outer = parts[0];

        foreach (var part in parts[1..])
        {
            var name = part;
            if (propertyNames.TryGetValue(outer, out var properties) && properties.Contains(part))
            {
                // A Type suffix, or the outer name as a prefix when the name already ends in Type
                name = part.EndsWith("Type", StringComparison.Ordinal) ? outer.Split("__")[^1] + part : part + "Type";
            }

            reference.Append('.').Append(name);
            outer += "__" + part;
        }

        return reference.ToString();
    }

    /// <summary>The name a type is declared with, the last part of its reference.</summary>
    public string SimpleName(string internalName) => TypeReference(internalName).Split('.')[^1];

    /// <summary>The types a nested type is declared in, outermost first, by internal name.</summary>
    public List<string> OuterTypes(string internalName)
    {
        var parts = internalName.Split("__");
        List<string> outers = [];

        for (var i = 1; i < parts.Length; i++)
        {
            outers.Add(string.Join("__", parts[..i]));
        }

        return outers;
    }

    private static bool IsNested(string internalName) => internalName.Contains("__", StringComparison.Ordinal);

    public string RootClass(string @class)
    {
        var rootParent = @class;
        while (classHierarchies.TryGetValue(rootParent, out var parent) && parent is not null)
        {
            rootParent = parent;
        }

        return rootParent;
    }

    /*
        CNmVelocityBlendNode::CDefinition -> VelocityBlendNode__CDefinition, then adjusted by the target
    */
    public string ConvertClassName(string cStyleClassName, string cStyleNamespacePreffix = "")
    {
        if (MatchingTypes.Contains(cStyleClassName))
        {
            return cStyleClassName;
        }

        if (target.TypeMap.TryGetValue(cStyleClassName, out var mappedType) || CommonTypeMap.TryGetValue(cStyleClassName, out mappedType))
        {
            return mappedType;
        }

        cStyleClassName = cStyleClassName.Trim();
        cStyleClassName = cStyleClassName.Replace("::", "__", StringComparison.Ordinal);

        var sb = new StringBuilder(cStyleClassName.Length);
        var parts = cStyleClassName.Split("__", StringSplitOptions.RemoveEmptyEntries);
        foreach (var part in parts)
        {
            var cleanPart = part;

            if (cleanPart.StartsWith('C') && cleanPart.Length > 1 && char.IsUpper(cleanPart[1]))
            {
                cleanPart = cleanPart[1..];
            }

            if (cleanPart.StartsWith(cStyleNamespacePreffix, StringComparison.Ordinal))
            {
                cleanPart = cleanPart[cStyleNamespacePreffix.Length..];
            }

            if (cleanPart.EndsWith("_t", StringComparison.Ordinal))
            {
                cleanPart = cleanPart[..^2];
            }

            if (sb.Length > 0)
            {
                sb.Append("__");
            }

            sb.Append(cleanPart);
        }

        return target.PostProcessClassName(sb.ToString());
    }

    public static string ConvertHungarianNotation(string name)
    {
        var stripInitial = "m_";
        Span<string> stripType = ["n", "b", "fl", "h", "s", "sz"];

        var newName = name;

        if (newName.StartsWith(stripInitial, StringComparison.Ordinal))
        {
            newName = newName[stripInitial.Length..];
        }

        foreach (var type in stripType)
        {
            if (newName.StartsWith(type, StringComparison.Ordinal) && newName.Length > type.Length && char.IsUpper(newName[type.Length]))
            {
                newName = newName[type.Length..];
                break;
            }
        }

        // capitalize first letter
        if (newName.Length > 0)
        {
            newName = char.ToUpper(newName[0], CultureInfo.InvariantCulture) + newName[1..];
        }

        return newName;
    }

    public void Write(SchemaType type, StringBuilder writer)
    {
        switch (type)
        {
            case SchemaEnum @enum:
                WriteEnum(@enum, writer);
                break;
            case SchemaClass @class:
                WriteClass(@class, writer);
                break;
        }
    }

    private void WriteEnum(SchemaEnum @enum, StringBuilder writer)
    {
        var enumName = ConvertClassName(@enum.Name, SourceNameSpace);
        var access = IsNested(enumName) ? "internal " : string.Empty;
        writer.Append(CultureInfo.InvariantCulture, $"{access}enum {SimpleName(enumName)} : {ConvertClassName(@enum.BaseType)}\n");
        writer.Append("{\n");

        foreach (var (name, value) in @enum.Members)
        {
            writer.Append(CultureInfo.InvariantCulture, $"    {name} = {value},\n");
        }

        writer.Append("}\n");
    }

    /*
        class CNmVelocityBlendNode::CDefinition : public CNmParameterizedBlendNode::CDefinition
        {
        };
        ------->
        [KV3Transfer]
        partial class VelocityBlendNode : ParameterizedBlendNode
        {
        }
    */
    private void WriteClass(SchemaClass @class, StringBuilder writer)
    {
        var convertedClass = ConvertClassName(@class.Name, SourceNameSpace);
        var access = IsNested(convertedClass) ? "internal " : string.Empty;

        var csClass = $"{access}{target.ClassKeywords(this, convertedClass)} {SimpleName(convertedClass)}";
        if (@class.Parent is not null)
        {
            csClass += $" : {TypeReference(ConvertClassName(@class.Parent, SourceNameSpace))}";
        }

        writer.Append("[KV3Transfer]\n");
        writer.Append(csClass).Append('\n');
        writer.Append("{\n");

        foreach (var field in @class.Fields)
        {
            WriteMember(field, @class.Defaults.TryGetValue(field.Name, out var value) ? value : null, writer);
        }

        writer.Append("}\n");
    }

    private void WriteMember(SchemaField field, JsonElement? schemaDefault, StringBuilder writer)
    {
        var type = field.Type;
        var args = field.Args;
        var name = field.Name;

        // template types
        if (type is "CUtlLeanVector" or "CUtlLeanVectorFixedGrowable" or "CUtlVector" or "CUtlVectorFixedGrowable")
        {
            var templateArgs = args!.Split(',', 2, StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries);
            // Nested templates such as CStrongHandle< T > map by their outer name
            var itemType = ConvertClassName(templateArgs[0].Split('<', 2)[0], SourceNameSpace);
            type = $"{itemType}[]";
            args = null;
        }

        var newName = ConvertHungarianNotation(name);
        var csType = ConvertClassName(type, SourceNameSpace);

        if (DefaultKey(newName, csType) != name)
        {
            writer.Append(CultureInfo.InvariantCulture, $"    [KVProperty(\"{name}\")]\n");
        }

        var initializer = Initializer(csType, schemaDefault);
        var argComment = args is not null && args.Length > 0 ? $" // {args}" : string.Empty;

        writer.Append(CultureInfo.InvariantCulture, $"    public {TypeReference(csType)} {newName} {{ get; }}{initializer}{argComment}\n");
    }

    // Must match DefaultKey in the KV3Transfer source generator
    private static string DefaultKey(string propertyName, string csType)
    {
        var prefix = csType switch
        {
            "bool" => "b",
            "float" or "double" => "fl",
            "byte" or "sbyte" or "short" or "ushort" or "int" or "uint" or "long" or "ulong" => "n",
            _ => string.Empty,
        };

        if (prefix.Length > 0 || propertyName.Length == 0 || (propertyName.Length > 1 && char.IsUpper(propertyName[1])))
        {
            return "m_" + prefix + propertyName;
        }

        return "m_" + char.ToLowerInvariant(propertyName[0]) + propertyName[1..];
    }

    // The schema default as a property initializer, empty when it is the type's default value
    private string Initializer(string csType, JsonElement? schemaDefault)
    {
        // Arrays are never null, missing ones are empty
        if (csType.EndsWith("[]", StringComparison.Ordinal))
        {
            return " = [];";
        }

        if (schemaDefault is not { } value)
        {
            return string.Empty;
        }

        switch (csType)
        {
            case "bool":
                return value.ValueKind == JsonValueKind.True ? " = true;" : string.Empty;

            case "byte" or "sbyte" or "short" or "ushort" or "int" or "uint" or "long" or "ulong":
                return value.ValueKind == JsonValueKind.Number && value.GetRawText() != "0" ? $" = {value.GetRawText()};" : string.Empty;

            case "float" or "double":
                return value.ValueKind == JsonValueKind.Number && value.GetDouble() != 0 ? $" = {FloatLiteral(value.GetDouble(), csType)};" : string.Empty;

            case "Vector2" or "Vector3" or "Vector4" or "Quaternion":
                if (value.ValueKind != JsonValueKind.Array)
                {
                    return string.Empty;
                }

                var components = value.EnumerateArray().Select(c => c.GetDouble()).ToArray();
                var isIdentity = csType == "Quaternion" && components is [0, 0, 0, 1];
                if (components.All(c => c == 0) || isIdentity)
                {
                    return string.Empty;
                }

                return $" = new({string.Join(", ", components.Select(c => FloatLiteral(c, "float")))});";
        }

        if (enumTypes.Contains(csType) && value.ValueKind == JsonValueKind.String
            && enumMembers.TryGetValue(csType, out var members) && members.TryGetValue(value.GetString()!, out var memberValue))
        {
            return memberValue == 0 ? string.Empty : $" = {TypeReference(csType)}.{value.GetString()};";
        }

        return string.Empty;
    }

    private static string FloatLiteral(double value, string csType)
    {
        var suffix = csType == "float" ? "f" : "d";

        if (csType == "float" && Math.Abs(value) >= float.MaxValue)
        {
            return value > 0 ? "float.MaxValue" : "float.MinValue";
        }

        return value.ToString("R", CultureInfo.InvariantCulture) + suffix;
    }

    public static void Test(SchemaTarget target)
    {
        var converter = new Converter(new Schema { Types = [] }, target);

        Debug.Assert(converter.ConvertClassName("CUtlString", target.SourceNameSpace) == "string");
        Debug.Assert(ConvertHungarianNotation("m_flBlendTimeSeconds") == "BlendTimeSeconds");

        target.Test(converter);
    }
}
