name: Validate

#on:
#  push:
#    paths:
#      - GUI/Types/Renderer/Shaders/**

permissions:
  actions: write
  contents: write

jobs:
  uses: ssciwr/setup-mesa-dist-win@v2
  validate:
    run: dotnet run --project Misc/ShaderValidator
