name: Validate

on:
  push:
    paths:
      - GUI/Types/Renderer/Shaders/**
  pull_request:
    paths-ignore:
      - GUI/Types/Renderer/Shaders/**

permissions:
  contents: read

jobs:
  validate:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: mkdir
      run: dotnet build --project Misc/ShaderValidator

    - name: Set up OpenGL Software Drivers system-wide
      shell: cmd
      run: |
        curl.exe -L --output mesa.7z --url https://github.com/pal1000/mesa-dist-win/releases/download/20.3.2/mesa3d-20.3.2-release-msvc.7z
        "C:\Program Files\7-Zip\7z.exe" x mesa.7z
        mklink opengl32.dll "x64\opengl32.dll"
        mklink libglapi.dll "x64\libglapi.dll"
      working-directory: Misc/ShaderValidator/bin/Debug

    - name: Validate
      run: dotnet run --project Misc/ShaderValidator
